- src/layouts/mod.rs
I find this particularly useful when editing many files. It gives each window in the workspace the same width by arranging them into a number of columns, and then splits each column into so many rows.
Here's what it looks like with 5 windows:
And with 9 windows:
I also added some documentation & changed the other Layout structs to use a simpler syntax (no braces). I kept those style changes in their own commit though so that it should be easy to not merge them if you don't like it.
------
Thanks for making this window manager! I started using it just a few hours ago and I'm really loving how intuitive the default bindings are and how easy it is to get started with.
> Add a GridHorizontal layout, which splits the workspace into an even NxN grid (or as close as it can get)

- Cargo.lock
- Cargo.toml
- src/bin/leftwm-worker.rs
- src/bin/leftwm.rs
- src/handlers/command_handler.rs
- src/handlers/window_handler.rs
- src/models/manager.rs
- src/utils/child_process.rs
Collect all `Child`s in to a `Children` struct and use `SIGCHLD` signal handler. Reap zombies in every `event_loop` epoch.
Before this commit, `ps auxf` gives:
```
leftwm
\_ [dropbox] <defunct>
\_ /usr/bin/leftwm-worker
\_ [up] <defunct>
\_ [alacritty] <defunct>
\_ [alacritty] <defunct>
\_ [alacritty] <defunct>
\_ [rofi] <defunct>
```
After this commit, it's like:
```
leftwm
\_ /usr/bin/leftwm-worker
\_ alacritty
\_ ...
```
> Fix #89: close window leaving zombies

- README.md
- src/command.rs
- src/config.rs
- src/handlers/command_handler.rs
- src/utils/command_pipe.rs
This pull request adds a command that sends the current active window to the top of the stack. However, if the window is already on top of the stack, it sends it to second position.
By default, this would be mapped to `mod+enter`.
> New Command: master toggle

- src/models/dto.rs
Xmonad differentiates between tags that are not visible and tags that are not visible _and_ have windows. This is useful info to communicate to a status bar, so that the user doesn't forget about windows hanging around in hidden tags. For instance:
where **[3]** is a tag in the current workspace, **1** is a tag in another visible workspace (another monitor in this case) and **2** is a tag that it is not visible but has windows in it. The rest are not visible and are empty of windows.
<details><summary> Using this template </summary>
```vue
{% for tag in workspace.tags %}
{% if tag.mine %}
%{A1:$SCRIPTPATH/change_to_tag {{workspace.index}} {{tag.index}}:}
%{F#D19A66}%{B#455A64} [ {{tag.name}} ] %{B-}%{F-}
%{A}
{% elsif tag.visible  %}
%{A1:$SCRIPTPATH/change_to_tag {{workspace.index}} …
```
> Show which tags has windows in leftwm-state

- src/handlers/window_handler.rs
- src/utils/state_socket.rs
I guess moving Dock window to the top race with polybar re-stacking tray window: https://github.com/polybar/polybar/blob/1dc8d2f30e248d2ca186d7dcf2972c5111dc3fa2/src/x11/tray_manager.cpp#L581
I have no experience working with X, but in my case, it fixed the issue.
Fixes #138.
> Do not move Dock on the top of the stack

- src/command.rs
- src/handlers/command_handler.rs
- src/layouts/main_and_vert_stack.rs
- src/models/workspace.rs
this is my implementation to resize the main window using keybindings like in many other WMs as presented by @cjwyett in issue #144 (but only for the `main_and_vert_stack` layout for now)
although it does work as intended for me the PR is only meant as an idea as this is my first time modifying rust code and I probably violated many rust and/or leftwm concepts here and i'm not sure how the testing usually works with rust/leftwm
as a result of this code new keybindings can be used to change the size of the main window (for the one layout it was implemented for). The value represents width change as a percentage:
*[config.toml]*:
```
[[keybind]]
command = "IncreaseMainWidth"
value = "5"
modifier = ["modkey"]
key = "l"
[[keybind]]
command = "DecreaseMainWidth"
value = "5"
modifier = …
```
> resize windows with keybinding

- Cargo.lock
- Cargo.toml
- src/bin/leftwm-state.rs
- src/config/theme_setting.rs
- src/utils/child_process.rs
- src/utils/command_pipe.rs
Good afternoon,
This PR updates the following:
- dirs
- nix
- signal-hook
- liquid
Additionally, `cargo audit` notes the following:
```
Fetching advisory database from `https://github.com/RustSec/advisory-db.git`
Loaded 239 security advisories (from /home/mautamu/.cargo/advisory-db)
Updating crates.io index
Scanning Cargo.lock for vulnerabilities (140 crate dependencies)
Success No vulnerable packages found
warning: 1 warning found
Crate:  dirs
Title:  dirs is unmaintained, use dirs-next instead
Date:   2020-10-16
URL:    https://rustsec.org/advisories/RUSTSEC-2020-0053
Dependency tree:
dirs 2.0.2
Crate:  dirs
Title:  dirs is unmaintained, use dirs-next instead
Date:   2020-10-16
URL:    https://rustsec.org/advisories/RUSTSEC-2020-0053
Dependency tree:
dirs 3.0.1
Crate:  term
Title:  term …
```
> Bump versions on outdated packages

- src/layouts/main_and_horizontal_stack.rs
- src/layouts/mod.rs
Adds a new layout, similar to the "bstack" layout in this [dwm patch](https://dwm.suckless.org/patches/bottomstack/).
The code is more or less a complete copy to `src/layouts/main_and_vert_stack.rs`, except a few changes here and there, so should work fine.
I have tested on my laptop.
> main & horizontal stack layout

- src/layouts/center_main_balanced.rs
- src/layouts/mod.rs
I've added a new layout for personal use and thought I would see if there's some interest in merging it.
The layout separates the screen into three columns, leaving a column in the middle much like the "center main" layout, and distributing the windows through the other columns in a manner similar to the fibonacci layout but "row first".
I've found it particularly useful on my ultra-wide.
> Added "center main balanced" layout

- src/bin/leftwm-check.rs
- src/bin/leftwm-state.rs
Good morning,
Per #168, and kind of #27, I think it would be helpful to have a binary that I have called cargo-check.  As currently implemented, it will tell you if your configuration is right or give a TOML error if it is wrong. I think it could be expanded to:
1. verify whether a theme is installed properly (verify theme config is correct)
2. perhaps only be compiled as an optional feature for debugging purposes
3. propose suggestions for fixing the config.toml file
4. read config.toml files from other locations to check them as well (although Clap currently says it will take input, it won't)
Any thoughts? As it is written now, it is a bit messy in output. I found it helpful in developing a solution to #32 that I intend to finish soon.
Best, 
Mautamu
> Leftwm-check

- src/config/theme_setting.rs
- src/layouts/mod.rs
- src/models/margins.rs
- src/models/mod.rs
- src/models/window.rs
- src/models/window_change.rs
Good evening,
This PR adds functionality to the margins as per #194. I went with the HTML format of [top, right, bottom, left] and [top/bottom, left/right]. To change the margins, edit _~/.config/leftwm/themes/current/theme.toml_ from:
```toml
border_width = 4
margin = 10
```
to:
```toml
border_width = 4
margin = [10, 10]
```
I intended to apply this to borders as well, but it does not appear that this is possible due to an upstream requirement of a singular integer to define borders, but it may be possible.
> Add more specific margin capabilities

- src/handlers/focus_handler.rs
- src/handlers/goto_tag_handler.rs
- src/handlers/screen_create_handler.rs
- src/models/dock_area.rs
- src/models/window.rs
- fix a type preventing test suites from being run on `cargo test`. `[#cfg(tests)] becomes `[cfg(test)]`
- fix tests that stopped working after recent changes to tags
> test suite fix

- src/layouts/main_and_horizontal_stack.rs
- src/layouts/mod.rs
- src/layouts/monocle.rs
As proposed in #174 here is my attempt to add a simple Monocle Layout, which sets the primary window to full screen and hides any others. The windows can be cycled through with MoveWindow commands.
In a hacky way it get rid of the margin, but I am not sure how to handle properly to return to the theme margin again in other layouts, yet.
Also it would be possibly nice to have a monocle specific margin, like doule or tripple the theme margin. Maybe have a "monocle-factor" value in the theme.toml?
> monocle Layout

- README.md
- themes/README.md
Howdy,
This PR modifies the README.md and themes/README.md to:
- Include information about LeftWM Theme
- Add a table of contents for easier reading
- More closely follow the Markdown standards by linting
- Add more consistent branding
There is an accompanying wiki modification, located at https://github.com/mautamu/leftwm_wiki that makes similar changes as described in #218.
Best,
Mautamu
> Update README with LeftWM-theme information, and other information as well. Partially resolves #218

- themes/basic_polybar/polybar.config
Fixes issue where seconds in basic polybar config, shown upon click of
time, was erroneously placed after the AM/PM instead of after the
minutes.
Fixes #240
> Fix position of seconds in basic_polybar date-alt

- README.md
Clarifies manual installation process.  User can copy/paste commands leading to fewer configuration errors.  Tested this process on Ubuntu, Arch and Solus
> Documentation installation

- src/handlers/external_command_handler.rs
- src/utils/command_pipe.rs
As requested [here](https://github.com/leftwm/leftwm/pull/243#issuecomment-804003368).
I haven't tested that this super thoroughly, and just went based on grepping the codebase for instances of other external commands, so I've marked it as a draft in case somebody else who has better knowledge of how `ExternalCommand`s work can test and verify the changes.
If something is wrong, just let me know and I'll be happy to fix it.
> Add SetLayout as external command

- src/layouts/mod.rs
- src/models/workspace.rs
> Fixed Typo `LeftWiderRi(g)htStack` and fix for `SetLayout` not working properly with `LeftWiderRightStack` and `RightWiderLeftStack`

- src/state.rs
This restores the original window order when reloading, in as fast a way I can think of (let me know if anyone can find ways of speeding it up). This will causes conflicts with #259, as the addition to remember margin multiplier won't be added, but this will be an easy conflict to fix.
> Restore window order on reload

- src/bin/leftwm-worker.rs
- src/display_event.rs
- src/display_servers/xlib_display_server/event_translate.rs
- src/display_servers/xlib_display_server/mod.rs
- src/display_servers/xlib_display_server/xwrap.rs
- src/handlers/command_handler.rs
- src/handlers/display_event_handler.rs
- src/handlers/focus_handler.rs
- src/handlers/window_handler.rs
Every so often xlib fails to send us Window EnterNotify events. This means we don't get notified that the cursor has moved over a window. That means focus is left in the previous window not the new window we just moused over. This Update its to address this issue.
> Update to focus system to watch for missed EnterEvents

- src/display_servers/xlib_display_server/event_translate.rs
- src/handlers/command_handler.rs
@mautamu I appreciate your help cleaning up the code base. I thought I would help out too. I don't want to step on your toes with this project so if you want to take a different route that's cool with me. Here is a start of a refactor of the two big switch blocks. I have taken the content of each branch and pulled them out into a function. That is all. There should be no logical changes in this PR. 
My thinking here is its much easier to work with smaller functions. I could organize them into different files or refactor the contents individually. this is just a step one...
> Refactor large functions into smaller ones

- themes/basic_lemonbar/template.liquid
- themes/basic_polybar/template.liquid
- themes/basic_xmobar/template.liquid
Related to #177 
Since this feature needs some documentation, a good way is to just show it to newcomers. 
__1__ is visible (other monitor), __2__ is busy (with windows, but not visible) and __3__ is owned tag:
* Polybar
* XMobar
* Lemonbar
I tried to respect the style of the theme, but any change is welcome!
Simply modified the `template.liquid` files for each basic theme.
> Docs: add busy indicator to basic themes

- src/utils/helpers.rs
vec_extract inspired by drain_filter() (which currently is in rust nightly). Using the basic test:
```
#![feature(drain_filter)]
use std::ptr;
use std::time::Instant;
fn main() {
//Check the arrays are correct
let vec: Vec<u32> = (0..=100).collect();
let mut list = vec.clone();
let test = vec_extract(&mut list, |x| *x % 2 == 0);
println!("{:?}, {:?}", list, test);
let mut list2 = vec.clone();
let test2 = vec_extract2(&mut list2, |x| *x % 2 == 0);
println!("{:?}, {:?}", list2, test2);
let mut list3 = vec.clone();
let test3 = vec_extract3(&mut list3, |x| *x % 2 == 0);
println!("{:?}, {:?}", list3, test3);
let vec: Vec<u32> = (0..=1000).collect();
//Performace tests
let start = Instant::now();
for i in 1..=1000 {
let mut list = vec.clone();
vec_extract(&mut list, |x| *x % i == 0);
} …
```
> Faster vec_extract: Testing requested

- src/utils/helpers.rs
Similar to my over pull request, just with cycle_vec (much greater improvement). Testing code:
```
use std::time::Instant;
fn main() {
//Check the arrays are correct
let vec: Vec<u32> = (0..=100).collect();
let mut list = vec.clone();
cycle_vec(&mut list, -5);
println!("{:?}", list);
let mut list2 = vec.clone();
cycle_vec2(&mut list2, -5);
println!("{:?}", list2);
//Performace tests
let vec: Vec<u32> = (0..=1000).collect();
let start = Instant::now();
let mut x = 600;
for _i in 1..=1000 {
let mut list = vec.clone();
cycle_vec(&mut list, x);
x *= -1;
}
println!("{:?}", start.elapsed() / 1000);
let start2 = Instant::now();
for _i in 1..=1000 {
let mut list = vec.clone();
cycle_vec2(&mut list, x);
x *= -1;
}
println!("{:?}", start2.elapsed() / 1000);
}
pub fn cycle_vec<T>(list: &mut Vec<T>, …
```
> much faster cycle_vec

- src/utils/helpers.rs
This improves the speed when dealing with the manual reordering and massively reduces the needed code. Test:
```
use std::time::Instant;
fn main() {
//Check the arrays are correct
let vec: Vec<u32> = (0..=100).collect();
let mut list = vec.clone();
reorder_vec(&mut list, |x| *x == 0, -5);
println!("{:?}", list);
let mut list2 = vec.clone();
reorder_vec2(&mut list2, |x| *x == 0, -5);
println!("{:?}", list2);
//Performace tests
let vec: Vec<u32> = (0..=1000).collect();
let start = Instant::now();
let mut x = 600;
for _i in 1..=1000 {
let mut list = vec.clone();
reorder_vec(&mut list, |x| *x == 800, x);
x *= -1;
}
println!("{:?}", start.elapsed() / 1000);
let start2 = Instant::now();
for _i in 1..=1000 {
let mut list = vec.clone();
reorder_vec2(&mut list, |x| *x == 800, x);
x *= -1;
} …
```
> faster reorder_vec with manual reordering

- src/models/workspace.rs
- src/utils/window_updater.rs
As mentioned in #170, #174. Was there a reason for this check?
While testing with fullscreen I have found a bug where if a window that is fullscreened loses focus to a window below it. However it only loses focus to the window if it is above in the list. I am planning on creating an exclusive fullscreen through leftwm and could fix this by moving it up in the stack (but it then wouldn't return to the same position) and this wouldn't fix it if the window makes it's self fullscreen.
Also should all windows on a tag where a window is fullscreen be set invisible (would this also fix the previous issue?)?
Closes #170.
Thanks
Edit: I also made the windows that are on the same screen as a full screen window not get turned visible, which has indeed fixed the focus issue and setups nicely for a …
> Stop fullscreen window being 'sticky', and hide non-fullscreen windows on the workspace

- src/display_servers/xlib_display_server/xwrap.rs
Support for encoded window names, to make named scratchpads possible. Also should the for loop be changed with if ptr_len > 0.
Thanks.
> Support encoded window names

- src/display_servers/xlib_display_server/mod.rs
- src/display_servers/xlib_display_server/xwrap.rs
- src/handlers/command_handler.rs
- src/handlers/focus_handler.rs
- src/models/workspace.rs
Howdy,
This PR prepares for Clippy 0.1.53 to hit the CI by updating some tests to avoid for_each and a .cloned().
Best,
Mautamu
> Update for Clippy 0.1.53 (42816d6 2021-04-24)

- README.md
- src/bin/leftwm-command.rs
This is basically a wrapper for sending external commands into commands.pipe. It allows for simpler syntax in doing so and allows you to chain commands (where commands with args must be surrounded in quotes).
Thanks.
> Leftwm-Command

- src/bin/leftwm-check.rs
- src/config.rs
Howdy,
A number of folks (myself included) have had issues setting up leftwm on non-systemd machines. This adds a lint to leftwm-check which ensures that:
1. Either XDG_RUNTIME_DIR is specified presently, and warns if it isn't;
2. Or, the loginctl command (as a proxy for elogind) exists.
Closes #307 .  Tagging  @byfw and #228.
Best,
Mautamu
> Adds check to leftwm-check for XDG_RUNTIME_DIR/elogind. Closes 307.

- themes/basic_lemonbar/change_to_tag
- themes/basic_lemonbar/down
- themes/basic_lemonbar/up
- themes/basic_polybar/change_to_tag
- themes/basic_polybar/down
- themes/basic_polybar/up
- themes/basic_xmobar/change_to_tag
- themes/basic_xmobar/down
- themes/basic_xmobar/up
- themes/controlling_leftwm/change_to_tag
- themes/controlling_leftwm/move_window_to_last_workspace
- themes/controlling_leftwm/move_window_to_tag
- themes/controlling_leftwm/swap_screens
This is to allow these themes to be applied without patching in systems where `bash` is installed in a different location.
E.g. FreeBSD, `/usr/local/bin/bash`.
Thank you.
> Make themes more portable.

- src/config/theme_setting.rs
- src/handlers/external_command_handler.rs
- src/handlers/screen_create_handler.rs
- src/layouts/mod.rs
- src/models/gutter.rs
- src/models/mod.rs
- src/models/window.rs
- src/models/workspace.rs
Adds margins to workspaces, this closes #327 as the user could now add a gap their selves at the top of the workspace if the automatic system doesnt work. This also closes #194 and closes #270, as if you add half the margin you want to workspace and the other half to window, the gap will be consistent. E.g. if you want a gap of 8 consistently, if you set window_margin to 4 and workspace_margin to 4, all the gaps will be 8.
The reason the theme config breaks is because margin has changed to window_margin to be more clear, but this isn't necessary if we don't want to break the config.
Thanks.
> Add margins and gutters to workspace

- src/bin/leftwm-check.rs
Howdy,
This adds a fallback to "NONE" for git-version, thus closing #346.
Best,
Mautamu
> Add fallback for git version, closes #346

- src/bin/leftwm.rs
I'm not sure why, but I find it really irritating to type `leftwm-theme` rather than `leftwm theme`. So I implemented four subcommands for `leftwm`:
+ `leftwm check`
+ `leftwm command`
+ `leftwm state`
+ `leftwm theme`
If you run any of these, it will simply run the corresponding program e.g. `leftwm-theme` rather than attempting to start the window manager. If you call it with no arguments, it will function as normal and attempt to start the window manager.
Further arguments will be passed to the corresponding program, so `leftwm theme update` will run `leftwm-theme update`.
> Add subcommands to leftwm

- src/handlers/command_handler.rs
- src/handlers/goto_tag_handler.rs
- src/handlers/window_handler.rs
- src/models/dto.rs
- src/models/manager.rs
- src/models/window_change.rs
- src/state.rs
- src/utils/window_updater.rs
Rework of #361. I felt that the previous attempt unnecessarily updated the tags for the docks to often taking unneeded processor time (not matter how little). This now only updates the tags of the windows with a strut when a change occurs (the strut changes or we move to a different tag). I am not 100% we need the code in state, I guess it catches windows that don't get relaunched on reload.
Thanks.
Now fixes #366.
> Be more efficient when updating bar tags

- src/display_servers/xlib_display_server/event_translate.rs
- src/display_servers/xlib_display_server/xwrap.rs
- src/handlers/mouse_combo_handler.rs
This fixes when moving/resizing in clickto mode would cause the window to be stuck to the cursor.
Thanks.
> Fix move/resize when in ClickTo mode

- src/bin/leftwm.rs
As pointed out by @VuiMuich [here], subcommands had some weird behaviours.
1. `leftwm state` would give you your prompt back immediately and then run in the background (vomiting all over your terminal whenever window manager actions occurred) rather than staying alive and allowing you to stop it with `Ctrl+C`. This was because we weren't `.wait()`ing for the command to finish before exiting.
2. `leftwm state -q` and other such commands were being considered invalid by `clap`. This is because clap does not know about the arguments to the external subcommands, so it thinks they are all invalid.
`1` was an easy fix, we just needed to `.wait()` on the subcommand.
`2` does not have an obvious fix - I was unable to find a way to get `clap` to accept arbitrary arguments to subcommands as valid. …
> Fix subcommands continuing in background, fix clap errors showing for valid arguments to subcommands

- src/utils/helpers.rs
Closes #328
I don't really get, why this caused only crashes with `FocusWindow{Up/Down}` and not also with `Move...` but it seems like this fixed it.
Could you please verify I am not overlooking any possible case, where `relative_finde` returning `None` is actually expected? I beleive this is not the case, but not 100% sure.
> Fix focus crash

- src/bin/leftwm-worker.rs
- src/handlers/command_handler.rs
- src/handlers/window_handler.rs
- src/models/dock_area.rs
- src/models/manager.rs
- src/models/window.rs
- src/state.rs
- src/utils/window_updater.rs
Fixes #387, with partial fixes for #388 and #390. In terms of #390 we can't (nicely) keep the window as fullscreen due to #386, as the window is restored in fullscreen briefly and gets minimised as the windows are still being re-added to the manager which then minimises it (if there is a way to hold the state being reloaded until all previous windows are loaded into the new manager, that I feel would be the easiest way). With #388 I think I have squashed any crashes around main_and_deck (If anymore are found let my know), but the focusing weirdness may require handling the focus change differently (I not 100% sure if this can be solved elegantly atleast with the issues I have found where the focus is sloppy and a floating window is above the centre of the next window to focus, meaning the …
> Various fixes

- src/bin/leftwm.rs
Not much more to say beyond the title I guess.
I was thinking of adding a bit of logic to print the git hash only when it actually has some, but then decided to do the same as `leftem-check` with the `"NONE"` string.
> Add `git-hash` to `leftwm -V` output

- src/display_servers/xlib_display_server/event_translate.rs
This is a quick fix for #394. I thinking about reworking how we handle windows such that we don't need to forget them when they are unmapped and using unmap to hide a window when it is invisible.
Thanks.
> Fixes #394

- src/bin/leftwm-state.rs
- src/config.rs
- src/config/workspace_config.rs
- src/display_servers/xlib_display_server/event_translate.rs
- src/display_servers/xlib_display_server/mod.rs
- src/display_servers/xlib_display_server/xwrap.rs
- src/handlers/command_handler.rs
- src/handlers/focus_handler.rs
- src/handlers/window_handler.rs
- src/handlers/window_move_handler.rs
- src/layouts/mod.rs
- src/models/manager.rs
- src/models/screen.rs
- src/models/tag.rs
- src/models/window.rs
- src/models/xyhw.rs
- src/utils/child_process.rs
- src/utils/helpers.rs
- src/utils/xkeysym_lookup.rs
This is mostly adding semicolons and removing ampersands. Also renames the struct WorkspaceConfig to Workspace as it ended in the containing module's name.
Thanks.
> Update for clippy 0.1.54

- src/handlers/focus_handler.rs
We can clone just `WindowHandle` instead of the whole `Window`
> focus_handler: cheaper `clone` operation in `move_focus_to_point`

- src/handlers/focus_handler.rs
Clones only the first workspace tag, not all of them.
Also, unless I really need sleep, the current function panics since it specifically checks if `tags` is empty and then goes on to access the first element of `tags` anyway.
This behavior no longer happens under the proposed changes
> focus_handler: don't clone all workspace tags, only the one being set

- src/display_action.rs
- src/display_servers/xlib_display_server/mod.rs
- src/display_servers/xlib_display_server/xwrap.rs
- src/handlers/command_handler.rs
- src/handlers/focus_handler.rs
- src/handlers/window_handler.rs
- src/models/focus_manager.rs
- src/models/mod.rs
- src/models/window_change.rs
Hey,
This pull request fixes a problem i had.
When switching to an empty tag from a tag where a window had focus, the window on the previous tag would still have the focus.
This can be very annoying since you could still perform actions on this window while it was not visible.
I fixed this issue by telling LeftWM to focus an imaginary window with an arbitrary handle value, which seems to work fine for now.
I had to adapt some code for this to work on the first focus of a tag.
> Unfocus last window when switching to an empty tag

- src/bin/leftwm-check.rs
Adds a check for the modifier keys when editing leftwm config.
Previous behaviour would allow modifier keys to be anything even when they were not a valid key.
Will output an error when the modifier key is not valid!
> Add check for modifier keys

- src/bin/leftwm-check.rs
- src/bin/leftwm-state.rs
Howdy,
This PR adds an error message for leftwm-check when multiple commands are given the same keybinding.
It therefore closes #464 .
Test Case:
```toml
[[keybind]]
command = "PreviousLayout"
modifier = ["modkey", "Control"]
key = "Down"
[[keybind]]
command = "NextLayout"
modifier = ["modkey", "Control"]
key = "Down"
```
Yields:
```
:: LeftWM version: 0.2.9
:: LeftWM git hash: 0375604-modified
:: Loading configuration . . .
-> Configuration loaded OK
:: Checking keybinds . . .
ERROR: Multiple commands bound to key combination modkey + Control + Down:
-> PreviousLayout
-> NextLayout
Help: change one of the keybindings to something else.
:: Checking environment . . .
-> Environment OK
:: Checking theme . . .
-> Theme OK
```
If three or more are issued, it throws an error for each n+1
Best, …
> Warn for duplicate keys; closes #464

- src/layouts/center_main.rs
- src/layouts/center_main_balanced.rs
This PR partly addresses issue #96.
With this update, changing the main-width (`IncreaseMainWidth` and `DecreaseMainWidth`) is now possible in the `CenterMain` layout.
Having an ultra-ultra wide 49' inch monitor, this feature is a lifesaver for me :)
**Update 2021/09/12**
I made an update to the code:
- Fixed a pre-existing bug in the `x` positioning of the primary window, when two windows were open on a workspace where `workspace.x()` is **not** `0`.
- Added the same feature to the `CenterMainBalanced` layout.
> allow changing main_window size in CenterMain/CenterMainBalanced layouts

- src/display_action.rs
- src/display_event.rs
- src/display_servers/xlib_display_server/event_translate.rs
- src/display_servers/xlib_display_server/mod.rs
- src/display_servers/xlib_display_server/xwrap.rs
- src/handlers/display_event_handler.rs
Hi,
Lately I changed my keyboard layout to `dvorak`, but Leftwm wouldn't pick up the changes resulting in me not being able to use the keybindings. The symptoms and temporary solution, `pkill lefwm-worker` on startup, were similar to issue #163 (this pull request possibly fixes this issue).
**The fix:**
- Leftwm did not refresh the key mapping on a `MappingNotify` event -> added an extra `match` case
- After the remapping, the keys needed to be regrabbed
- Some plumbing to get all necessary information together for the regrabbing
Kind regards,
SamClercky
Ps. Some useful links:
- [Stackoverflow xlib keyboard changes](https://stackoverflow.com/questions/35569562/how-to-catch-keyboard-layout-change-event-and-get-current-new-keyboard-layout-on)
- [Example implementation in …
> Fix broken keybinds when keyboard layout changes

- src/event_loop.rs
So who wants more Windows update :grin: 
I checked the code and I think this code was triggered almost every time after a command from CommandPipe **except** for the commands called from `display_event_handler.rs` (key combos).
In this PR I'm **not** restoring that exact behavior. I am updating the windows systematically after any command no matter the origin (from pipe or from key binding) as suggested by @AethanFoot https://github.com/leftwm/leftwm/pull/472#issuecomment-932345059
My reasoning is that it is better to have consistency across command handling. The commands triggered by `display_event_handler.rs` are for when a key combo occurs while the ones triggered in the event loop are for when a command is received via the command pipe. It seems more predictable and consistent that …
> Hotfix: missing windows update after command

- src/bin/common/command.rs
- src/bin/common/config.rs
- src/command.rs
- src/handlers/command_handler.rs
- src/utils/command_pipe.rs
Adds command MoveWindowToNextWorkspace and MoveWindowToPreviousWorkspace. 
Should focus follow the window?
Thanks.
> Add commands to move window to next/previous workspace

- .gitignore
- leftwm-core/src/handlers/mouse_combo_handler.rs
This simple fix closes #518.
The `state.focus_window()` is now called before the method returns, so that the focus changes when moving an out-of-focus window in the `ClickTo` focus behavior.
---
I wanted to do the same for window resizing to allow resizing windows which are out-of-focus. This doesn't seem to be possible though, as no `XEvent` is emitted when an out-of-focus is right-clicked.
---
Also updated the `.gitignore` file after git tried to commit my `leftwm-core/target` directory :)
> Change focus when mod key is held down (ClickTo)

- leftwm-core/src/config/mod.rs
- leftwm-core/src/display_servers/mod.rs
- leftwm-core/src/display_servers/xlib_display_server/mod.rs
- leftwm-core/src/display_servers/xlib_display_server/xwrap/getters.rs
- leftwm-core/src/display_servers/xlib_display_server/xwrap/mod.rs
- leftwm-core/src/event_loop.rs
- leftwm-core/src/handlers/command_handler.rs
- leftwm-core/src/handlers/display_event_handler.rs
- leftwm-core/src/handlers/focus_handler.rs
- leftwm-core/src/handlers/goto_tag_handler.rs
- leftwm-core/src/handlers/mouse_combo_handler.rs
- leftwm-core/src/handlers/screen_create_handler.rs
- leftwm-core/src/handlers/window_handler.rs
- leftwm-core/src/models/dto.rs
- leftwm-core/src/models/manager.rs
- leftwm-core/src/models/window.rs
- leftwm-core/src/models/workspace.rs
- leftwm-core/src/state.rs
- leftwm-core/src/utils/state_socket.rs
- leftwm/src/config.rs
This PR is an attempt to help doing "soft" reloading.
If I understand it properly. The current reloading system is to hard reload because soft reloading does not work properly for now. In This PR I will try to enumerate the issues and fix them.
> Improve configuration soft reloading

- leftwm-core/src/handlers/command_handler.rs
- leftwm-core/src/utils/helpers.rs
I saw that the `relative_find` logic was implemented redundantly in `focus_tag_change`. The method now also uses the pre-existing helper method.
After looking at the code, I realized that it had some bugs, for example: on a list of length `1` the only element in the list was always returned, even if `should_loop` was set to false. I've re-implemented the method and added tests to verify the implementation. Please let me know if you think a test-case is missing.
> relative_find helper: fix bug, add tests, add docs, remove duplicate code

- leftwm-core/src/handlers/command_handler.rs
- leftwm-core/src/handlers/goto_tag_handler.rs
- leftwm-core/src/models/layout_manager.rs
- leftwm-core/src/models/tag.rs
- leftwm-core/src/state.rs
Fixes a regression reported by aethan in #557.
The `all()` methods returned a clone of the tag-list, mutating it did therefore not affect the actual state.
I rewrote so `all()` returns actual borrowed values, rather than cloned ones and introduced `all_mut()` in case the tags should be mutable.
I'm not a 100% sure if that's the best way to do it, please let me know if you have any opinions on that.
> fix regression from #557, restore tag state on reload

- leftwm-core/src/handlers/command_handler.rs
- leftwm-core/src/handlers/window_handler.rs
This PR fixes #564 by addressing the following issues:
1. In the sloppy behavior, when the focus window moves to another (out of sight) tag, it may still keep the focus
1. In any focus-behavior, when the last window on a workspace is moved to another (out of sight) tag, it keeps focus
1. When the only window on a workspace is destroyed, the focus is just re-applied to it instead of unfocusing all windows
The issues 2 and 3 may not be fixed properly with this PR alone, it  also requires the fixes in #565 to be present. 
> In detail: before #565 the `relative_find()` method would always return the single element in the list if the list is of size `1`. In case of the `get_next_or_previous()` method, this means that on a workspace with only one window, the helper method always returned the …
> Properly handle focus when window is destroyed / moved to another tag

- leftwm-core/src/display_servers/xlib_display_server/xwrap/setters.rs
As discussed on Discord, commit 589dc71d2a98500c83c2a94210d4d2e80773bc7b introduced a minor regression where _NET_CURRENT_DESKTOP started at `1` instead of `0`. This PR should fix this as suggested by @hertg :)
> Fix wrong _NET_CURRENT_DESKTOP index.

- README.md
Was a dead link, I think the change now points it to the intended enum.
> Fix layout link.

- leftwm/src/bin/leftwm-check.rs
It was meant to fix bug #576, however the function which runs checks on `theme.toml` had the same issue. Hopefully I fixed that as well.
leftwm-check.rs
* if the verbose argument was false, `check_permissions` function was always returning Ok(filepath) 
* same thing with `check_theme_toml`, all the essential checks were inside `if verbose` block
> Fixed leftwm-check not running essential checks if verbose arg is false (#576)

- .github/workflows/ci.yml
- README.md
I thought we should rename our main branch to `main` instead of `master`.
Every new projects on GitHub now uses "main" by default and to be honest it feels weird now when I read "master".
More on the subject: https://www.theserverside.com/feature/Why-GitHub-renamed-its-master-branch-to-main
After merging this you need to go to the settings of the project and rename the branch there too and that's all.
Locally though, everybody who don't want to re-clone the project needs to update the default branch using this command:
```
git remote set-head origin --auto
```
It's `origin` if the remote is origin but it can be `upstream` depending on your local set up:
```
git remote set-head upstream --auto
```
**Note:** re-cloning the repo will default to main and no action is needed.
> Rename branch master to main

- leftwm-core/src/config/mod.rs
Without the `DisplayServer` trait boundary, it is not possible to call the function `command_handler` from inside a custom command handler:
```
error[E0599]: the method `command_handler` exists for mutable reference `&mut Manager<Config, SERVER>`, but its trait bounds were not satisfied
--> leftwm/src/cecile.rs:224:35
|
224 |                 let res = manager.command_handler(Command::GotoTag(i));
|                                   ^^^^^^^^^^^^^^^ this is an associated function, not a method
|
= note: found the following associated functions; to be used as methods, functions must have a `self` parameter
note: the candidate is defined in the trait `leftwm_core::Config`
--> /home/cecile/repos/leftwm/leftwm-core/src/config/mod.rs:36:5
|
36  | /     fn command_handler<SERVER>(command: &str, …
```
> Fix missing trait boundary for custom command handler

- leftwm-core/src/handlers/window_handler.rs
- leftwm-core/src/models/size.rs
- leftwm-core/src/models/workspace.rs
I have no idea why those have been limited to 90% but I can assure you it works fine. I made a scratchpad with xterm at 0,0 of size 100%x50% and it just looks like quake3
:thinking: .... I wonder if this could be related to window border and gaps... In my config I have 0 border and 0 gap so I can actually use 100% safely.
cc @tramhao @VuiMuich @hertg @AethanFoot 
Related to #493
> Allow scratchpad sizing at 100% (aka "Q3 console")

- leftwm-core/src/command.rs
- leftwm-core/src/config/mod.rs
- leftwm-core/src/handlers/command_handler.rs
- leftwm-core/src/utils/command_pipe.rs
- leftwm/src/bin/leftwm-command.rs
- leftwm/src/command.rs
- leftwm/src/config.rs
This is a simple thing I was missing coming from XMonad, so figured I
would add it as it turned out to be fairly simple to do.
I'm not super fan of the implementation though, maybe the helper method
should be renamed to something else, or a new method added in
`command_handler`, e.g. `focus_window_top`.
Ideally, I would like to add the ability to go back to the previously
focused windowed by pressing the key again, just not sure how to do that
yet.
> feature: implement FocusWindowTop command

- leftwm-core/src/layouts/grid_horizontal.rs
- leftwm-core/src/layouts/mod.rs
This pull request implements #612. 
I implemented only a horizontal flip, as that seemed to be the desired use case. Adding the vertical flip would be trivial, but would require adding 2 more rotation states (which may not be desired). If the vertical flip is desired, I can implement that before completing this pull request.
> Rotate grid horizontal

- leftwm-core/Cargo.toml
- leftwm/Cargo.toml
Tagging @lex148, sorry these are close together this seemed an important patch. To also summarise for you, we are aligning the versioning closer to semantic e.g. MAJOR.MINOR.PATCH. This will allow us to add backwards compatible patches without needing to push new features that were added (possibly adding more bugs, and doesn't delay helpful patches by a feature not being done), then features can be added along minor iteration and be more spread out, then #292 will cause a major iteration (e.g. a 1.0.0 release).
Tagging @0323pin and @rigoletto-freebsd again so you know what is happening.
> Version bump.

- leftwm-core/src/display_servers/xlib_display_server/xwrap/getters.rs
On FreeBSD/powerpc64le:
```
Compiling leftwm-core v0.2.10 (/wrkdirs/usr/ports/x11-wm/leftwm/work/leftwm-0.2.10/leftwm-core)
Running `CARGO=/usr/local/bin/cargo CARGO_CRATE_NAME=leftwm_core CARGO_MANIFEST_DIR=/wrkdirs/usr/ports/x11-wm/leftwm/work/leftwm-0.2.10/leftwm-core CARGO_PKG_AUTHORS='Lex Childs <lexchilds@gmail.com>' CARGO_PKG_DESCRIPTION='A window manager for Adventurers' CARGO_PKG_HOMEPAGE='' CARGO_PKG_LICENSE=MIT CARGO_PKG_LICENSE_FILE='' CARGO_PKG_NAME=leftwm-core CARGO_PKG_REPOSITORY='https://github.com/leftwm/leftwm' CARGO_PKG_VERSION=0.2.10 CARGO_PKG_VERSION_MAJOR=0 CARGO_PKG_VERSION_MINOR=2 CARGO_PKG_VERSION_PATCH=10 CARGO_PKG_VERSION_PRE='' CARGO_PRIMARY_PACKAGE=1 LD_LIBRARY_PATH='/wrkdirs/usr/ports/x11-wm/leftwm/work/target/release/deps:/usr/local/lib' /usr/local/bin/rustc …
```
> Fix build errors on architectures with u8

- .github/workflows/ci.yml
- .gitignore
- flake.lock
- flake.nix
This PR adds a flake.nix for people using NixOS. It makes it easy to install the latest version of leftwm, as well as running custom branches.
It also provides a shell with the minimal tooling required to work on leftwm. This can be called through `nix-direnv` or directly with `nix develop`
> feat: provide a Nix Flake for NixOS

- flake.nix
- leftwm/src/bin/leftwm-check.rs
- leftwm/src/bin/leftwm.rs
Just a small improvement to #639 to include the git hash when building on NixOS, as `nixpkgs` will copy the source tree to an empty folder before building, thus `git_version` can't detect the hash.
> fix: git commit missing on nixos

- leftwm-core/src/event_loop.rs
- leftwm-core/src/utils/command_pipe.rs
- leftwm/src/bin/leftwm-command.rs
This change allow running multiple session of leftwm. Without this, the
second session would destroy the file of the first one, leaving it
unsuable.
> fix: include display id in command pipe name

- README.md
Hello. LeftWM is now in the XBPS repos for Void Linux. Updating README should be fine :smile: 
Relevant PR: https://github.com/void-linux/void-packages/pull/31657
> Add Void Linux to README

- leftwm-core/src/config/workspace_config.rs
- leftwm-core/src/models/layout_manager.rs
This makes the `layouts` field in workspace config optional.
This was mainly a little papercut, when workspaces are setup manually, but share the same set of layouts.
> Make workspace layouts an option

- leftwm/src/bin/leftwm-check.rs
- leftwm/src/config/checks.rs
- leftwm/src/config/mod.rs
This fixes a report from Discord, by user Jalish#4407, that the line `Theme OK` did not reset the terminal color. So when no prompt styling is present any further characters in the terminal are printed in green.
While allready at this I fixed this for all `println` in `leftwm-check.rs`.
> [bugfix] `leftwm-check` didn't reset color

- leftwm-core/src/display_servers/xlib_display_server/xwrap/keyboard.rs
Hey there! 
I'll bother you with some allocation-related PRs yet again :v
> Avoid heap allocation in `keyboard::grab_keys`

- leftwm-core/src/handlers/window_handler.rs
- leftwm-core/src/models/xyhw.rs
This PR fixes the dialog windows getting cut off error by centering them in the workspace if their lower right corner is outside the workspace.
Since I'm starting with Rust, please let me know if there are more "idiomatic" ways of implementing it.
I'm eager to learn, thanks!
> fix: dialogue windows getting cut-off (#668)

- leftwm-core/src/handlers/command_handler.rs
- leftwm-core/src/handlers/focus_handler.rs
Ensure `focus_workspace` saves the last window on the tag before
switching, and then restores it for the next workspace
Resolves #641
> fix(641): focus the last window in the workspace

- leftwm-core/src/display_action.rs
- leftwm-core/src/display_servers/mod.rs
- leftwm-core/src/display_servers/xlib_display_server/event_translate.rs
- leftwm-core/src/display_servers/xlib_display_server/event_translate_client_message.rs
- leftwm-core/src/display_servers/xlib_display_server/event_translate_property_notify.rs
- leftwm-core/src/display_servers/xlib_display_server/mod.rs
- leftwm-core/src/display_servers/xlib_display_server/xatom.rs
- leftwm-core/src/display_servers/xlib_display_server/xwrap/getters.rs
- leftwm-core/src/display_servers/xlib_display_server/xwrap/mod.rs
- leftwm-core/src/display_servers/xlib_display_server/xwrap/mouse.rs
- leftwm-core/src/display_servers/xlib_display_server/xwrap/setters.rs
- leftwm-core/src/display_servers/xlib_display_server/xwrap/window.rs
- leftwm-core/src/event_loop.rs
- leftwm-core/src/handlers/command_handler.rs
- leftwm-core/src/handlers/display_event_handler.rs
- leftwm-core/src/handlers/focus_handler.rs
- leftwm-core/src/handlers/mouse_combo_handler.rs
- leftwm-core/src/handlers/window_handler.rs
- leftwm-core/src/models/manager.rs
- leftwm/src/config/mod.rs
This reduces the xlib calls by 1: removing calls that don't add anything, 2: focus events are self contained and no longer makes moving/resizing calls, 3: only make the windows move/resize when needed (this mainly involves returning false in command_handler/display_event_handler when the windows don't actually move/resize, not returning true/false depending on whether it succeeded). Maybe more to come.
Thanks.
> Reduce xlib calls and other optimisations

- leftwm/src/config/mod.rs
Removes the `Vec` allocation and uses the `Iterator`-based `find` which the compiler _should_ optimize better
> Slight refactoring of `default_terminal`

- .github/workflows/ci.yml
- leftwm-core/src/command.rs
- leftwm-core/src/handlers/command_handler.rs
- leftwm/src/bin/leftwm-command.rs
- leftwm/src/command.rs
- leftwm/src/config/keybind.rs
This command focuses a window with the given `WM_CLASS`. 
- If the window is not present, it does nothing
- If the window is visible in any workspace, it will gain focus
- If the window is not visible, the current workspace will switch to a tag with the window and give it focus
- If the window is hidden in the `Monocle` or `MainAndDeck` layout, it will scroll the layout so that the window becomes visible and focused
- If the window is already focused, it will focus the previousely focused one, following the same rules
Example configuration:
```toml
[[keybind]]
command = "FocusWindow"
value = "brave-browser" # The first or the second entry of WM_CLASS attribute
modifier = ["modkey"]
key = "b"
```
Another added possibility is to focus a visible window by its index on the screen. Example …
> FocusWindow command

- leftwm/src/config/checks.rs
This fix the config check showing a warning about id collision when all
workspaces have ID and none are duplicates.
> fix: workspace id validation

- themes/basic_eww/template.liquid
- themes/basic_lemonbar/template.liquid
- themes/basic_polybar/template.liquid
- themes/basic_xmobar/template.liquid
- The polybar template included three spaces instead of two for 'busy' tags, which caused an inconsistent layout.
- The else statements on all bar templates had a `tag.visible` condition (probably a copy/paste error).
> Fix spacing and else statements on liquid templates

- leftwm-core/src/command.rs
- leftwm-core/src/handlers/command_handler.rs
- leftwm-core/src/utils/command_pipe.rs
- leftwm/src/config/keybind.rs
- command `MoveWindowTop` in core allows disabling/enabling automatic swap
- changed `FocusWindowTop` to use struct variant instead of tuple variant (for clarity sake)
- turned `move_focus_common_vars` into a macro to allow flexibly pass any kind and number of parameters
- command in config toml `MoveWindowTop` now accepts a boolean value to disable/enable the swapping (enabled by default to avoid breaking compatibility)
- `MoveWindowTop` can be passed (optional) with a boolean argument in the command pipe. Defaults to swap: true (to avoid breaking change... though I think `false` would be better there imo)
No breaking change has been introduced (hopefully :grin:)
> Allow disabling swap for MoveWindowTop

- leftwm-core/src/display_servers/xlib_display_server/xwrap/window.rs
This partially fixes #735, namley:
> **Border colors for floating/non-floating windows seem to get mixed up**
When I switch focus from a tiled window to a floating window, the previously focused tiled window gets the `floating_border_color`. When switching focus from a tiled to another tiled window, this doesn't happen. The floating window seems to never receive the `floating_border_color` at all.
---
Issue simply was, that on window focus change, when changing the previous window's border color, the newly focused windows properties were considered to decide on the previous window's border colors :stuck_out_tongue:
> Fix border-color issue when focusing a floating window

- leftwm-core/src/command.rs
- leftwm-core/src/handlers/command_handler.rs
- leftwm/src/command.rs
- leftwm/src/config/keybind.rs
Similarly to GoToTag feature, I wanted a way to unconditionally go to
previous tag, without having to press the key for the current tag.
No default keybindings have been assigned for this feature.
I did not find an up to date list of available commands so I did not
know where to document this new command.
Tested in Xephyr. `cargo test` passes.
> Add GoToPreviousTag feature to unconditionally go to last visited tag

- leftwm-core/src/config/mod.rs
- leftwm-core/src/handlers/window_move_handler.rs
- leftwm/src/config/default.rs
- leftwm/src/config/mod.rs
Add disable_window_snap config option as mentioned in #561 
I would update the config wiki page as below.
If snapping is enabled, floating windows are snapped (repositioned to a tile) when the window  is dragged close to a Workspace edge. This might lead to undesired behaviour when dragging windows near the edge of the screen, so it is disabled by default.
Snapping can be disabled with `disable_window_snap`:
Default: `disable_window_snap = true`
Example: `disable_window_snap = false` (enables snapping)
> Allow disabling window snapping

- leftwm-core/src/command.rs
- leftwm-core/src/handlers/command_handler.rs
- leftwm-core/src/utils/command_pipe.rs
- leftwm/src/bin/leftwm-command.rs
- leftwm/src/command.rs
- leftwm/src/config/keybind.rs
Add moving window to the next or previous tag.
When executing while working on first/last tag, the command will move window wrapping around tag list.
Fixes #751
...
Takes the window that is currently focused and moves it to the next tag. If `value` is `true`, the focus will follow the window. Next tag is brought to the current workspace and focused.
Example:
```toml
[[keybind]]
command = "MoveWindowToNextTag"
value = "true"
modifier = ["modkey", "Shift"]
key = "l"
```
Takes the window that is currently focused and moves it to the previous tag. If `value` is `true`, the focus will follow the window. Previous tag is brought to the current workspace and focused.
Example:
```toml
[[keybind]]
command = "MoveWindowToPreviousTag"
value = "true"
modifier = ["modkey", "Shift"]
key = "h"
```
... …
> Add moving window to next/previous tag (#751)

- README.md
Picom has been added to official Arch repos a couple of years ago, no need to provide a command to get it from AUR.
README.md
> README: Changed picom command for Arch

- Makefile
In my opinion it's a little bit annoying to call `cargo clippy -- -W clippy::pedantic -A clippy::must_use_candidate -A clippy::cast_precision_loss -A clippy::cast_possible_truncation -A clippy::cast_possible_wrap -A clippy::cast_sign_loss -A clippy::mut_mut` manually on the command line, so I added `test-full` which does `make test` and this long clippy command.
Fixes #(issue)
Not needed
> adding the `test-full` label

- README.md
Polybar is [in the archlinux community repository now][1], so there's no need to use `paru` or `yay` to install it.
[1]: https://archlinux.org/packages/community/x86_64/polybar/
> Update README: Polybar no longer requires an AUR helper on arch

- leftwm-core/src/config/mod.rs
- leftwm-core/src/models/layout_manager.rs
- leftwm-core/src/models/manager.rs
Since this struct seems be only used for `tests`, I thought that I could move it to the `tests` module then.
Not needed
> Move `TestConfig` to `tests` module

- leftwm-core/src/handlers/window_handler.rs
I wanted to fix #700 by using the window size / location hints when spawn_floating is configured. I don't think I fully fixed this, because we probably want to have a better default than falling back to "fullscreening" the window if it doesn't have a max height/width. Some windows define min width / height, this could be used as default width / height. I'd say this can be done in a separate PR.
As a side effect #632 will also be ~~fixed~~ partly fixed because windows will receive the last location / size as hint. ~~I don't know if this is application specific or something that is built into X, so I don't know if this completely fixes #632. This behavior is similar to the one from i3 for floating windows.~~ This only applies to apps that manually save the location / size and then set them …
> Floating window improvements

- leftwm/src/config/default.rs
- leftwm/src/config/mod.rs
A mention in #791 of the `state` config field and the following invstigation led to the decision a rename of `leftwm::config::Config::state` to `leftwm::config::Config::state_path` might help to prevent confusion with the actual `leftwm_core::state::State`.
Snuck in some typo fixes in comments along.
No user doc update needed.
> change confusing name for `state_file` path config option

- leftwm-core/src/utils/command_pipe.rs
In leftwm-core/src/utils/command_pipe.rs there was a missing match arm for ReturnToLastTag, preventing this command to work externally.
> Add missing match arm for external ReturnToLastTag command

- leftwm/src/bin/leftwm-command.rs
Adding missing entry in leftwm-command command list for ReturnToLastTag
> Add missing entry in leftwm-command command list for ReturnToLastTag

- leftwm-core/src/handlers/window_handler.rs
When some window was `fullscreen` and exits to `normal` mode windows of type `dock` don't recieve clicks anymore (tested with `eww` and `stalonetray`).
not applicable
> fix `dock` windows not recieving `click` after some window was `fullscreen`

- leftwm-core/src/event_loop.rs
- leftwm-core/src/state.rs
- fix a regression introduced in #820 that `restore_state` was unable to finish successful
- in `restore_state` renamed `state` to `old_state` for more clarity
- fix another deviation by #820 from the original code in the `event_loop` that lead to improper focus handling
> fix restore state regression

- leftwm-core/src/handlers/window_handler.rs
After recent refactors the fix of #822 was sort of neglected.
Putting the sorting after the update of `dock` windows seems to solve it again.
> fix #822 again

- .github/workflows/discussions-qa.yml
Adding a Github Action to automatically notify our Discord `#support` channel about new questions in the Github discussions tab. I'm proposing this addition as part of [my comment](https://discord.com/channels/889371782388256818/889374673593331712/1006664686516830331) on Discord.
> I was thinking whether we should "move" the support channel towards the Github Discussions Q&A?
Just because of 1. Question discoverability (via search engines etc) and 2. because the same questions pop up from time to time.
We could still leave the channel open and create a Github Workflow to post here when a new Q&A pops up. And maybe leave it as is for more chat-like back and forth when going into detail on something.
To merge this, the `DISCORD_WEBHOOK` secret must be configured on the repository. I have …
> Add github action to notify discord about Q&A

- .gitignore
This PR is only relevant for (neo-)vim users who use the
[`toggletasks.nvim`](https://github.com/jedrzejboczar/toggletasks.nvim) plugin
since it needs a json file where they can write their execution tasks. This
should be probably ignored for the most users, at least that's what I think.
It *could* be probably useful for other neovim users as well though.
Not needed
> Ignorting .toggletasks.json

- .github/workflows/ci.yml
Bump MSRV to 1.57.0 to suffice dependency needs for #821.
~~Our most consarvative target distro has been NetBSD and they use currently 1.62.1, yet I'd like to keep the bump as low as possible.~~
> bump MSRV to 1.57.0

- leftwm/src/bin/leftwm-worker.rs
- leftwm/src/config/mod.rs
When building without lefthk we would get an error as `config.keybind` does not exist. For some reason having a `cfg(feature...)` is not allowed above setting an attribute in this situation so I made a function.
> fix building with no features

- leftwm-core/src/models/scratchpad.rs
- leftwm/src/bin/leftwm-check.rs
- leftwm/src/config/default.rs
- leftwm/src/config/mod.rs
The newtype `ScratchPadName` did not define a way to convert to `String` (only from `String` to `ScratchPadName`). This gave the problem that the migration of `TOML` to `RON` introduced extra `(` and `)` around the scratchpad name and thus generating a bad config.
This PR also adds a test which tests that the (de)serialization can go in 2 ways. To make the test initially fail, a default scratchpad config was added to the `Default` impl of `Config`. The parameters were taken from the LeftWM wiki.
Fixes #860
See [CONTRIBUTING.md User Documentation …
> FIX: make leftwm-check -m migrate scratchpads correctly

- leftwm-core/src/handlers/window_handler.rs
In #863 this line was refactore out, as it seemed to have no purpose.
Turns out it actually had:
It makes sure the new window is put in the correct stacking layer.
Without this line it can happen, that new windows overlap floating windows like `rofi` or some `scratchpad` window, which should not happen.
This PR updates the comment line, hopefully provideng better information, what this line is here for.
> Fix new windows always getting stacked topmost

- README.md
as pointed out by @NicTanghe it was not clear where to get the desktop file from, when installing from crates.io directly. Should be clearer now.
Fixes #(issue)
> Add link to `leftfwm.desktop` to the README

- Makefile
There is no need to run clippy in release mode. Clippy is only a linter and this just slows down make test as the previous compiles all compile in development mode (all code has to be compiled again just for clippy, can't use cache).
Also, there is no mention of the --release flag in the [clippy readme](https://github.com/rust-lang/rust-clippy#step-3-run-clippy).
> No need to run clippy in release mode.

- themes/basic_eww/theme.ron
- themes/basic_eww/theme.toml
- themes/basic_eww/up
- themes/basic_lemonbar/theme.ron
- themes/basic_lemonbar/theme.toml
- themes/basic_lemonbar/up
- themes/basic_polybar/theme.ron
- themes/basic_polybar/theme.toml
- themes/basic_polybar/up
- themes/basic_xmobar/theme.ron
- themes/basic_xmobar/theme.toml
- themes/basic_xmobar/up
Just realised we did not update the theme examples to ron.
> update theme examples to ron

- leftwm/src/config/mod.rs
This PR adds a field to the window configuration in `window_rules`.
This field is called `spawn_as_type` and is a way for the user to set the [window type](https://specifications.freedesktop.org/wm-spec/latest/ar01s05.html#idm45374033166992) of a specific window with the usual rules via a config change.
Fixes #766 
Follow up to #879
Other references #631 
Add this to your `config.ron` file in the `window_rules` section:
```ron
#![enable(implicit_some)]
(
...
window_rules: [
...
( window_title: "Picture-in-Picture", spawn_as_type: Normal ),
...
]
...
)
```
> feat: Add a `spawn_as_type` to the `window_rules` configuration

- .github/pull_request_template.md
- Makefile
Added `test-nix` and `test-full-nix` to Makefile, plus a note in the pr template.
`make-test-nix` should now reproduce all CI checks.
You will of course have to install nix to run this.
> Added nix tests to Makefile.

- Makefile
The current `make install-dev` does not really describe what it does. It build leftwm in release mode and then links these files. I renamed it to `install-linked` and added `install-linked-dev` to build and link in development mode.
This change is breaking, as some scripts may invoke `make install-dev`, but I consider this a minority and a simple fix.
> Add install-linked-dev to Makefile

- leftwm-core/src/config/mod.rs
- leftwm-core/src/handlers/command_handler/mod.rs
- leftwm-core/src/handlers/command_handler/scratchpad_handler.rs
- leftwm-core/src/handlers/window_handler.rs
- leftwm-core/src/models/manager.rs
- leftwm-core/src/state.rs
- leftwm/src/config/default.rs
- leftwm/src/config/mod.rs
This PR adds a configuration option `single_window_border`.
Its default is `true` but if set to `false` it removes the border of a window if it is the only one on its tag.
Motivation: I mostly only have one window open on a given tag. A border there just uses unnecessary space because it's obvious where the window ends.
On https://github.com/leftwm/leftwm/wiki/Config:
**Single Window Border**
This shows a border on windows even if they are the only normal window on their tags.
Default: `single_window_border: true`
> No single border

- README.md
- leftwm/doc/leftwm.1
- leftwm/src/bin/leftwm.rs
As of #747 the new utility [leftwm-config](https://github.com/leftwm/leftwm-config) was created. This PR creates a subcommand to this utility and updates documentation to contain info about it. 
Fixes #658 
In the README.md I've added info about leftwm-config to Configuration block. Also updated manpage file. 
> Add leftwm config subcommand

- Makefile
Make clippy pedantic fail on warnings, like the ci does. This is for me so I can run `make test-full && git push` and leave my Laptop. To be exact, the ci only runs `cargo clippy -- -Dwarnings`, but I only added i to the clippy pedantic check. You should run `make test-full`, not `make test` anyways before committing.
Edit: Also moved the make calls to be like in the install scripts.
> Make `test-full` fail on warnings

- Makefile
- flake.nix
This change just fixes little things in the `Makefile`:
- Made the `install-linked-dev` rule build the project in debug mode, since it's linking files in `./target/debug`
- Changed the install dir for the `install` rule from `/usr/bin` to `TARGET_DIR`, which is `/usr/local/bin`, so it gets cleaned up with the `uninstall` rule
- `clean` now removes the `./result` symlink, which appears after building with `nix build`
- removed the invocation of `sudo` in the `test-nix`. If you can't use it without `sudo`, you should check if you are in the `nix-users` group
- added the `--verbose` flag for `test-nix`, so we get more info when building
This also fixes some deprecated declarations on `flake.nix`, which were triggering warnings with `test-nix`.
There is one that remains tho, its the …
> Some fixes for the `Makefile` and `flake.nix`

- display-servers/xlib-display-server/src/xwrap/mod.rs
- display-servers/xlib-display-server/src/xwrap/setters.rs
- leftwm-core/src/config/mod.rs
- leftwm-core/src/event_loop.rs
- leftwm-core/src/utils/child_process.rs
- leftwm/src/config/mod.rs
- leftwm/src/theme_setting.rs
- Added `background_color` field to the theme config on request of @VuiMuich.
- Changed some theme handling, specifically printing the all error messages when failing to run a script.
Add `background_color: "#333333"` to the example in the to rename Border Colors section.
- Make (all) colors optional?
- Which default color?
> Add `background_color` to theme config

- .github/workflows/ci.yml
- Cargo.lock
- leftwm-core/Cargo.toml
- leftwm/Cargo.toml
- leftwm/src/bin/leftwm-check.rs
- leftwm/src/bin/leftwm-command.rs
- leftwm/src/bin/leftwm-state.rs
- leftwm/src/bin/leftwm.rs
Bump crates to latest version
- tracing
- liquid
- clap
- nix
- ron
Close [RUSTSEC-2021-0139](https://rustsec.org/advisories/RUSTSEC-2021-0139) with the bump of `tracing`.
Migrate usage of `clap` stuff to version 4.
> bump several depedencies

- leftwm/src/bin/leftwm-check.rs
- leftwm/src/bin/leftwm-command.rs
- leftwm/src/bin/leftwm-state.rs
- leftwm/src/bin/leftwm-worker.rs
This should make `leftwm-check` working again.
Fixes #(993) (only half)
Not needed
> Fix binary arguments (clap)

- leftwm/src/bin/leftwm-check.rs
- leftwm/src/bin/leftwm-command.rs
- leftwm/src/bin/leftwm-state.rs
- leftwm/src/bin/leftwm.rs
- leftwm/src/utils/mod.rs
Didn't get merged with #937, so I cherry-picked my commit over.
Now the Author and version is printed again with the help pages.
> Make help pages work

- leftwm-core/src/handlers/command_handler/scratchpad_handler.rs
- leftwm-core/src/utils/child_process.rs
- leftwm/build.rs
- leftwm/src/bin/leftwm-check.rs
- leftwm/src/command.rs
- leftwm/src/config/mod.rs
Sometimes I am a bit of a moron and merge without letting CI finish, so here is a fix for the missed `fmt`.
But this gives the chance to fix some clippy lints that are unrelated to the previously merged PR and are new in rust 1.65 I guess.
> Clippy and fmt

- Cargo.toml
- Makefile
- README.md
- Added an `optimized` build profile.
- Adjusted `Makefile`, can now build with any profile.
Specify profile=<profile> in the make command arguments to select. Default is `optimized`.
- Adjusted `README.md` to account for changes.
Except they notice the slight performance increase or lower binary size
In the extremely rare case of some user scripts relying on `make install-linked-dev`
I lerned to hate Makefile syntax. And oh boy, do I hate it.
> Add optimized build profile

- leftwm/src/bin/leftwm-check.rs
- leftwm/src/config/mod.rs
- leftwm/src/theme_setting.rs
This activates the `implicit_some` extension of ron by default for all deserialisation. If the file (config or theme) explicitly activates it should be no issue.
This is especially helpfull since #922 made all fields of `theme.ron` optional.
> use `implicit_some` extension in ron deserializer

- leftwm/build.rs
Only print the warning message about necessary session restart only when no binary for `lefthk-worker` is found.
To be precise, we don't print on any error when trying to launch `lefthk-worker` as this means the same for the session state I guess.
> Print `lefthk` warning only when no binary present

- leftwm/build.rs
Discussion with @VuiMuich on the latest commit.
Fixes build on NetBSD
Not required.
`cargo-fmt` is happy 😄
> Exclude NetBSD in `build.rs` and avoid build-hangs

- display-servers/xlib-display-server/src/event_translate_client_message.rs
Reverts leftwm/leftwm#887
as reported by @0323pin this PR creates issues with Firefox.
Sorry for the inconvenience if anyone affacted.
> Revert "Fix regression that `wmctrl` and `rofi` could not request focus for a window"

- README.md
As the manual install instructions say to use the `optimized` profile, cargo places the builds in `./target/optimized`, not `./target/release`.
> Fix manual install instructions

- Cargo.lock
- leftwm/Cargo.toml
- leftwm/src/config/mod.rs
Allow regexps for matching window_class and window_title in leftwm config.
Resolves: #977
Signed-off-by: Ilya Trefilov <ilya.trefilov@outlook.com>
This change introduces regexp matching of window_class, window_title in window_rules config field. 
Fixes #977
Window rules allow to define how a window matching some properties should be spawned. As of now, a window can be matched by two properties:
window_class, string or regular expression corresponding to the property WM_CLASS of a window in a X server.
window_title, string or regular expression corresponding to the _NET_WM_NAME or the WM_NAME of a window. Both will be inspected if a window rule is defined by window_title. This takes precedence over window_class, since it is more specific.
The properties of a window can be inspected by …
> feat(config): allow regexps in window_rules for window_class,

- Makefile
Recently in a thread on the discord, @mautamu asked whether the theme templates of the repo get installed to a general accessible path.
With this PR the makefile installs the theme templates from the repo directory `./themes` to `/usr/share/leftwm` (and removes the directory with the uninstall), same as both our AUR packages do.
Should we reflect this in the Docs somewhere?
> handle theme templates within Makefile

- display-servers/xlib-display-server/Cargo.toml
Add some metadata fields to the manifest of the `display-server` crate so it could be published on `crates.io`
> add missing metadate to display-server crate

- leftwm-core/src/command.rs
- leftwm-core/src/handlers/command_handler.rs
- leftwm-core/src/utils/command_pipe.rs
- leftwm/src/command.rs
- leftwm/src/config/keybind.rs
This PR introduces a new Command `SwapWindowTop`, which swaps the current window with the window on top of the stack, without changing the order of the other windows. 
Fixes #1004 
Add section to (https://github.com/leftwm/leftwm/wiki/Config#keybind-commands) : 
Swaps the focused window with the window on top of the stack in the current workspace.  Takes an Optional argument swap, if set to false, calling the command while the top window is focused results in no action. Otherwise it will swap the top window with the one below it.  By default swap is set to true 
Add row to the External Commands table with the same describtion
> Add Command SwapWindowTop 

- CHANGELOG
Add `[Unreleased]` section to changelog and already include #1005. 
We can keep the Changelog up-to-date continuously rather than having to write the whole thing on next release :)
> add 'unreleased' section to changelog

- leftwm/src/config.rs
#986 (fe42fd0c0b6137823541510b3e118a52b28c673b) seems to introduce a small regression about calculating score window : for the class window, res_class and res_name was used and for the title window, name and legacy_name. Now, only res_class and legacy_name are used. This PR reintroduce the old behaviour.
> Fix regression on calculating window score

- leftwm-core/src/errors.rs
- leftwm/src/bin/leftwm-state.rs
While playing around with the `liquid` templates for `leftwm state`, I found that when an invalid template string was inserted, `leftwm state` would panic.
This PR changes the error output on wrong input `{{window_title}` from:
```
thread 'main' panicked at 'Unable to parse template: Error { inner: InnerError { msg: Owned(" --> 1:3\n  |\n1 | {{window_title}\n  |   ^---\n  |\n  = expected Literal"), user_backtrace: [Trace { trace: None, context: [] }], cause: None } }', leftwm/src/bin/leftwm-state.rs:92:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
to
```
liquid:  --> 1:3
|
1 | {{workspaces}
|   ^---
|
= expected Literal
Error: LiquidParsingError
```
Fixes #(issue) (I did not find any)
Should not be necessary
Note: To fully reproduce CI checks, you …
> Better error message for invalid liquid template strings

- leftwm/Cargo.toml
- leftwm/build.rs
Currently when `leftwm-check` outputs the enabled features and dependencies:
```
Enabled features: default journald-log lefthk lefthk-core tracing-journald
```
When the only enabled features are `journald-log` and `lefthk`. Using `feature = ["dep:dependency"]` is the intended way to do feature dependencies and therefore `leftwm-check` won't print all the dependencies it uses for those features:
```
Enabled features:  journald-log lefthk
```
I also trim `default` in `build.rs`.
This just basically makes `leftwm-check` a bit more readable.
> Fix `leftwm-check` outputting default and dependencies

- leftwm-core/src/event_loop.rs
- leftwm-core/src/utils/child_process.rs
No longer enforce that paths for `CommandPipe` need to be valid UTF-8 and drop a few heap allocations that were not needed, such as [this one](https://github.com/leftwm/leftwm/pull/1016/files#diff-f84f186acc1305f6ea6ffbf0647456df4ce1d52d2f1bebc6fc27548f59080292L184) or [this one](https://github.com/leftwm/leftwm/pull/1016/files#diff-f84f186acc1305f6ea6ffbf0647456df4ce1d52d2f1bebc6fc27548f59080292L199)
> Better manage paths in `event_loop`

- leftwm-core/src/utils/command_pipe.rs
Notifies stderr when CommandPipe's Drop impl fails to open pipe file with `O_NONBLOCK`. Also stops cloning `self.pipe_file` when doing so
> Notify user when CommandPipe's Drop impl fails to unlock pipe file

- leftwm-core/src/utils/command_pipe.rs
Sometimes command args get collected into a `Vec<&str>` during parsing, which is not needed.
By switching to using the `Split` iterator directly we can lower the latency of these parsing operations
> `command_pipe`: avoid heap allocating command parts when possible

- leftwm-core/src/handlers/command_handler.rs
(Yet more performance PRs :pleading_face:  please bear with me)
Attempts to improve performance of `set_layout`  by not allocating stuff on the heap, hopefully reducing latency
```rust
let tags_windows = state
.windows
.iter()
.filter(|w| w.has_tag(&tag_id) && w.is_managed() && !w.floating())
.collect::<Vec<&Window>>();
```
Here we were allocating a Vec of Window references when we only need the first two results of this filter, which we can do from Iterators alone
```rust
if let Some(w) = tags_windows.get(1).copied() {
to_focus = Some(w.clone());
}
```
`to_focus` now gets set to `tdw` directly since `tdw` was the second element of the list anyways. `to_focus` is now just a reference to `Window`, since we'll just need its handle at the end of the function
I also moved up the …
> Improve performance of `set_layout`

- display-servers/xlib-display-server/src/xwrap/getters.rs
- leftwm-core/src/handlers/focus_handler.rs
Allows for iterating through the user's XScreens and XRootOfScreens without allocating on the heap
Fixes #(issue)
> Less latency to get XScreens and XRootOfScreens

- leftwm-core/src/utils/state_socket.rs
Simple stylistic PR to simplify `state_socket` tests through `tokio::test`.
I'm not sure if the `block_on`s were intentional for some specific reason, please ignore the PR if they were. The tests remain the same other than that
> Simplify async tests with `tokio::test`

- leftwm/src/bin/leftwm-check.rs
I had a bad configuration (which I noticed because default config was used instead), so I ran `leftwm-check` to check the problem, and at first I thought there was a bug and it didn't catch the error, but it turned out that I just missed the error because it doesn't bring attention to itself (compared to theme errors).
WDYT about making it more visible just like some other errors?
> Make configuration errors more visible

- themes/basic_eww/README.md
Includes several changes to improve the `README.md` of the `themes/basic_eww` directory. It corrects phrasing, fixes typos, corrects the spelling of `GitHub`, highlights an important note, and adds backticks to format `eww`. 
These changes enhance the clarity and accuracy of the documentation.
> docs(themes/basic_eww): correct writing and improve formatting

- themes/basic_lemonbar/template.liquid
as raised on discord, the template was outdated.
The `liquid templating` section in the wiki should be checked, if it mentions the deprected `{{ localtime }}`
> fix `template.liquid` for `basic_lemonbar` example theme

- Cargo.lock
- leftwm/Cargo.toml
- leftwm/src/bin/leftwm-check.rs
Ran `cargo update` and ran into an issue that `git_version` failed on our way we implemented the fallback.
Fixed this.
Built against rust 1.70.0 (`make test-full`) and 1.65.0 (`cargo b` and `cargo r --bin leftwm-check`).
Edit: also fixes a `yanked` warning for `crossterm-channel` that is thrown by `cargo audit`
> bump deps and fix build error

- leftwm/src/bin/leftwm-log.rs
General improvements for leftwm-log
Default level is WARN, each `-v` increases it up to `-vvv` with TRACE.
**TODO**
> Improvements to leftwm-log

- leftwm-core/src/models/dto.rs
Fix an regression in #1043 that removed the output field from `leftwm-state`.
Fixes #1111
Note: Independent clippy warnings were ignored.
> Add back output field to leftwm-state

- .github/pull_request_template.md
- display-servers/xlib-display-server/src/event_translate_client_message.rs
- display-servers/xlib-display-server/src/event_translate_property_notify.rs
- display-servers/xlib-display-server/src/lib.rs
- display-servers/xlib-display-server/src/xatom.rs
- display-servers/xlib-display-server/src/xwrap/mouse.rs
- leftwm-core/src/display_servers/mock_display_server.rs
- leftwm-core/src/handlers/command_handler.rs
- leftwm-core/src/handlers/focus_handler.rs
- leftwm-core/src/handlers/window_handler.rs
- leftwm-core/src/handlers/window_resize_handler.rs
- leftwm-core/src/models/tag.rs
- leftwm-core/src/models/window.rs
- leftwm-core/src/models/workspace.rs
- leftwm-core/src/models/xyhw.rs
- leftwm-core/src/utils/child_process.rs
- leftwm-core/src/utils/modmask_lookup.rs
- leftwm/src/command.rs
- leftwm/src/config/default.rs
- themes/basic_eww/eww-bar/eww.scss
Spaced the doc comments consistently
Also silently fixing a self-made typo
> Space comments consistently

- Cargo.lock
- Cargo.toml
- leftwm-core/src/command.rs
- leftwm-macros/Cargo.toml
- leftwm-macros/src/lib.rs
- leftwm/Cargo.toml
- leftwm/src/bin/leftwm-command.rs
- leftwm/src/command.rs
Good afternoon,
This change implements #1095 by using a proc macro to collect the variants of the `BaseCommand` enum and their documentation comments for publication in `leftwm-command --list`.
Opens:
Fixes #1095
> feat: Derive `leftwm-command -l` list from BaseCommand enum using Proc Macro

- CHANGELOG.md
- display-servers/xlib-display-server/src/lib.rs
- display-servers/xlib-display-server/src/xwrap/getters.rs
- leftwm-core/src/command.rs
- leftwm-core/src/handlers/command_handler.rs
- leftwm-core/src/handlers/window_handler.rs
- leftwm-core/src/models/tag.rs
- leftwm-core/src/models/window.rs
- leftwm-core/src/models/window_state.rs
- leftwm-core/src/utils/command_pipe.rs
- leftwm/src/bin/leftwm-command.rs
- leftwm/src/command.rs
Add a `ToggleMaximized` command that covers everything except the bar, to make it easy to focus on a window without getting rid of the bar
Fixes #973
[External command wiki page](https://github.com/leftwm/leftwm/wiki/External-Commands) should be updated
> add `ToggleMaximized` command

- leftwm-core/src/config.rs
- leftwm-core/src/handlers/mouse_combo_handler.rs
- leftwm-core/src/state.rs
- leftwm/doc/leftwm.1
- leftwm/src/config.rs
- leftwm/src/config/default.rs
personally it annoys me when the cursor snaps to the bottom right corner when resizing, and I searched for an issue to see if anyone agrees, and saw a couple of people, so I'm submitting a PR to add the option to disable it via an option in the config file.
also I just threw together this PR pretty quick, so maybe it needs some changes, so I just wanted to get it out there so we can discuss it here
addresses #1011 
this page: https://github.com/leftwm/leftwm/wiki/Config
> add `disable_cursor_reposition_on_resize` option to config

- leftwm-core/src/handlers/command_handler.rs
- leftwm-core/src/models/tag.rs
- leftwm-core/src/models/window.rs
- leftwm-macros/src/lib.rs
I introduced a bug in #1121 that hides every window type except floating windows (I didn't know of this bug cus I didn't use a dock in my testing environment)
> fix invisible dock and desktop when maximizing a window

- Cargo.toml
- display-servers/xlib-display-server/src/lib.rs
- display-servers/xlib-display-server/src/xwrap/getters.rs
- display-servers/xlib-display-server/src/xwrap/setters.rs
- display-servers/xlib-display-server/src/xwrap/window.rs
- leftwm-core/src/handlers/focus_handler.rs
- leftwm-core/src/models/xyhw_change.rs
- leftwm-core/src/utils/child_process.rs
- leftwm/src/config.rs
- leftwm/src/config/default.rs
While reviewing code github presented some clippy lints in unrelated code. This adresses those.
A thing where I am not 100% certain if about the implications is the resolver config in `Cargo.toml`, here is the clippy lint for this:
```
warning: some crates are on edition 2021 which defaults to `resolver = "2"`, but virtual workspaces default to `resolver = "1"`
Warning: note: to keep the current resolver, specify `workspace.resolver = "1"` in the workspace root's manifest
note: to use the edition 2021 resolver, specify `workspace.resolver = "2"` in the workspace root's manifest
```
Also would be great, if anybody has an idea how githubs service to put clippy lints in code review is setup, so we could copy their flags in our Makefile checks.
Please insert user documentation that should be …
> [chorens] clippy lints

- leftwm-core/src/handlers/display_event_handler.rs
- leftwm-core/src/models/window.rs
This pr supersedes #1134, I used a simpler solution to respect the margins.
I also fixed the issue where the window wouldn't drop out of fullscreen/maximized when resized/moved.
There is also a slightly changed resize behavior now: When resizing a tiled window, the back ones instantly take it's space instead of after letting the window go. Tell me if you like it, it's just a question of using the third forced update statement or not.
This pr closes #1134
> Fix fullscreen resize and respect margins

- Cargo.lock
- leftwm/Cargo.toml
- leftwm/src/config/keybind.rs
Simple change to bump `lefthk` to 0.1.9, and support the new command types that come with that version.
> Bump `lefthk` to 0.1.9

- leftwm-core/src/config.rs
- leftwm-core/src/handlers/window_handler.rs
- leftwm-core/src/models/focus_manager.rs
- leftwm/doc/leftwm.1
- leftwm/src/config.rs
- leftwm/src/config/default.rs
This PR introduces the new configuration option `create_follows_cursor: Option<bool>`.
New windows will follow:
- the cursor if set to `Some(true)`
- the focus if set to `Some(false)`
- the cursor in `Sloppy` mode / the focus in any other mode if set to `None` or unset
Fixes #781
The [FocusBehaviour](https://github.com/leftwm/leftwm/wiki/Config#focus-behaviour) section of the documentation and man page should be updated accordingly with a paragraph resembling the description of this PR.
> Workspace selection for window placement

- display-servers/xlib-display-server/src/lib.rs
- display-servers/xlib-display-server/src/xwrap/window.rs
- leftwm-core/src/display_action.rs
- leftwm-core/src/handlers/command_handler.rs
- leftwm-core/src/handlers/display_event_handler.rs
- leftwm-core/src/handlers/window_handler.rs
- leftwm-core/src/models/window.rs
- leftwm-core/src/models/window_change.rs
- leftwm-core/src/state.rs
- Refactor to the window sorting to a cleaner solution.
- Refactor `Window.states` to `pub` (set and get methods were there, so why not make it it pub)
- Move from manually getting transient windows whilst sorting windows to adding the `Above` WM state to them.
- Side-effect: We now sort windows with the `Above` WM state on top of everything. Windows set this property on their own.
- As the window sorting now understands the `Above` WM hint, windows can set themselves to be on top.
- This pr places unmanaged windows above **all** windows instead of all but fullscreen. A visible unmanaged window is yet to be found, so it's not marked as breaking.
> Refactor window sorting

- leftwm-core/src/handlers/command_handler.rs
- leftwm-core/src/state.rs
Massively simplify #1052 by removing [line 124](https://github.com/leftwm/leftwm/blob/7628b688be4aafb155b1efdd09125de891e212a7/leftwm-core/src/state.rs#L124) from state.rs
Also a non-noticeable performance improvement by not having to do all the moves to restore the order.
> Rework fullscreen order restoring

- leftwm-core/src/models/tag.rs
Maximizing a window would make unmanaged windows invisible. Basically I forgot to remove the `&& w.is_managed()`
Fixes #1162
> Fix regression introduced in 4621dab

- leftwm-core/src/command.rs
- leftwm-core/src/handlers/command_handler.rs
- leftwm-core/src/handlers/window_handler.rs
- leftwm-core/src/models/tag.rs
- leftwm-core/src/state.rs
- leftwm-core/src/utils/command_pipe.rs
- leftwm/src/command.rs
Add a command to control `WindowState::Above`, `ToggleAbove`.
Fixes #1094 
This also makes a slight change to the detection of fullscreen changes: The old code triggered not only on change, but also whenever the window was already in fullscreen.
Add `ToggleAbove` to the command list.
> Add `ToggleAbove` command

- Cargo.lock
- leftwm/Cargo.toml
This bumps lefthk and lefthk-core to 0.2.0, which is the final step which fixes #1167. Previously, we published a leftwm-0.4.2-compatible lefthk and lefthk-core 0.1.10, published a leftwm-0.5.0-compatible lefthk and lefthk-core 0.2.0, and then yanked lefthk and lefthk-core 0.1.9.
Fixes #1167
None needed.
> chore: Bump lefthk to 0.2.0

- leftwm-core/src/handlers/window_handler.rs
Fixed an issue where leftwm would ignore the requested size of dialog-type windows when they are spawned, particularly when they are spawned without a parent. The previous behavior (which appears to be filling in the space left by the xyhw avoided) is still default when there is no desired size given. Additionally, this change has been carried over to splash screen windows and floating normal windows, just in case this issue applies to other windows with those types.
Fixes #1118 
N/A
> fixed dialog windows ignoring application-defined sizes

- .github/workflows/release.yml
- CHANGELOG.md
- Cargo.lock
- README.md
- display-servers/xlib-display-server/Cargo.toml
- leftwm-core/Cargo.toml
- leftwm-macros/Cargo.toml
- leftwm/Cargo.toml
This releases leftwm 0.5.0. Hoping to get #1168 included prior to this, so marking as draft for now.
**Note: Creating a GitHub Release/Tag will trigger crates.io to be updated, steps:**
1. [Draft a new release](https://github.com/leftwm/leftwm/releases/new)
2. Tag = (new tag), v0.5.0
3. Target = (this commit)
4. Release Title = v0.5.0
5. Set as a pre-release  = False
6. Set as the latest release  = True
7. Create a discussion for this release  = True
8. Ensure release goes smoothly, will be listed in the "Actions" tab
> chore: Release leftwm 0.5.0, XDS 0.1.2

- Cargo.lock
- leftwm/Cargo.toml
> bump to 0.5.1 to fix crates.io release

- .github/workflows/codeberg-mirror.yml
I took some time this afternoon and created a GitHub workflow to mirror the leftwm repo over to Codeberg.
- Mirror all branches on every push
- Mirror all prs under the `pulls/` branches (because we loose history when squashing)
- Only runs when `secrets.MIRROR_REPO` is set (accounting for forks)
Fixes #1053 
- Create ssh keys: `ssh-keygen -f ssh_key -N ''` (creates ssh_key and shk_key.pub files)
- `MIRROR_REPO` secret: `git@codeberg.org:leftwm/leftwm.git`
- `MIRROR_SSH_KEY` secret: content of generated ssh_key file
- Over on the mirror: add content of ssh_key.pub file as "Deploy Key" in repo settings
```bash
git fetch upstream "refs/*:refs/remote/upstream/*"
git push mirror "refs/remote/upstream/{heads,tags}/*"
git push mirror "refs/remote/upstream/pull/*/head:refs/heads/pull/*"
```
> Mirror to Codeberg

- leftwm/src/bin/lefthk-worker.rs
Simplify lefthk-worker by replacing the three feature checks by one module-wide one. 
> lefthk-worker: change multiple feature checks to one module condition

- Cargo.lock
- Cargo.toml
- display-servers/xlib-display-server/src/xwrap/getters.rs
- display-servers/xlib-display-server/src/xwrap/window.rs
- leftwm-core/src/utils/child_process.rs
- leftwm-watchdog/Cargo.toml
- leftwm-watchdog/src/main.rs
- leftwm-watchdog/src/utils.rs
- leftwm/Cargo.toml
- leftwm/src/utils.rs
Separate the leftwm(bin) target out of the leftwm crate into the leftwm-watchdog crate to improve compile times.
I changed the binary target's name to `leftwm` to avoid problems (this is now a development change, the target directory's executable are the same as before).
Fixes #1190 
> Separate leftwm bin

- Makefile
Someone forgot (probably me included) to put the new binary into the Makefile.
> Add leftwm-log to Makefile targets

- leftwm-core/src/handlers/window_handler.rs
I wasn't able to do a full review of #1166 before it was merged, but I had taken a look at the code and already noticed that the solution seemed complicated. However I kept it as a unread notification until when I had time (now).
Basically, the `set_relative_floating` function already respects all size requests, it just wasn't called.
This also corrects the mistake made before that (not respecting size hints from resizable dialog windows). However I wasn't able to trace that further than #807 (e2517de95)
> Rework "fixed dialog windows ignoring application-defined sizes (#1166)"

- display-servers/xlib-display-server/src/xwrap/setters.rs
`i64::from` was replaced by a direct `as` type cast. to fix the 32bit build error expressed in the issue below.
I don't expect this change to cause any problems as we are casting a smaller type (u32) into a larger one (c_long should be i64-eqivalent).
Compilation was tested on i686-unknown-linux-gnu toolchain.
Fixes #1201 
> Fix the 32 bit builds by changing a type cast

- display-servers/xlib-display-server/src/xwrap/setters.rs
- leftwm-core/src/handlers/command_handler.rs
- leftwm-core/src/handlers/command_handler/scratchpad_handler.rs
- leftwm-core/src/handlers/window_handler.rs
- leftwm-core/src/models/focus_manager.rs
This runs the latest clippy fixes following the release of 1.75.0; this does not appear to raise the MSRV. 
> chore: clippy fixes

- leftwm/src/config.rs
Remove hard coded default list of layouts
this enables users to define their own layouts using the default names "Monocle" and "MainAndDeck" which are hardcoded into other parts of leftwm.
Fixes #1127
*note* `make test` has failed saying that `X.get(0)` should be replaced by `X.front()` in multiple locations; it failed in the clippy step... perhaps related to #1198
> remove hardcoded default layouts

- leftwm/doc/leftwm.1
Fixes #1129
Adds explanation of `layouts` and `layout_definitions` entries in `config.ron` in the manpage
> update layouts in man page

- leftwm-core/src/handlers/window_handler.rs
- leftwm-core/src/models/workspace.rs
I encountered a bug after configuring a window hook for [PrismLauncher](https://github.com/PrismLauncher/PrismLauncher/) windows to be floating.
The "edit" window (normal type) does not request a height, The fallback was to use the workspace xywh, which caused it to clip into my bar up top.
This pr switches the full ws xywh to the xywh_avoided which considers margins.
> Fix newly spawned floating windows ignoring ws margins

- leftwm-core/src/handlers/command_handler.rs
- leftwm-core/src/handlers/window_handler.rs
Fixes what presumably is a regression I caused in #1158 where newly spawned and previously tiled floating windows aren't put up front but behind already existing ones. 
> [!NOTE]  
> I assume ignoring the `inset_behavior` config be intended behavior here.
> Spawn new floating windows above old ones

- leftwm-core/src/handlers/command_handler.rs
- leftwm-core/src/state.rs
remove default_width and default_height from State struct, get from Config instead.
Fixes #1212
> default_height and default_width

- leftwm-core/src/event_loop.rs
- leftwm-core/src/handlers/command_handler/scratchpad_handler.rs
- leftwm-core/src/utils/child_process.rs
Fixes #958. `ToggleScratchPad` was not working correctly. I changed the way `exec_shell` works to launch directly the command rather then first launch `sh -c`. The PIDs were always off by one, and I think that what was happening was that `sh` consumed one PID and then launched `alacritty` which consumed the next PID.
May be a breaking change for some users scratchpads, so should be tested I suppose.
> change exec_shell to directly executed given command

- display-servers/xlib-display-server/src/lib.rs
- display-servers/xlib-display-server/src/xwrap.rs
- leftwm-core/src/display_servers.rs
- leftwm-core/src/display_servers/mock_display_server.rs
- leftwm-core/src/handlers/command_handler.rs
- leftwm-core/src/models/manager.rs
- leftwm-core/src/state.rs
- leftwm/src/bin/leftwm-check.rs
- leftwm/src/config.rs
- leftwm/src/config/default.rs
- leftwm/src/lib.rs
- leftwm/src/theme_config.rs
Slightly rework the way the theme config is loaded into leftwm and untangle some of the color loading.
Fixes #(1213)
> [!Note]
> This pr is best reviewed per-commit, as there are a lot of renames.
- 2eace8188a226ebace36b7ddabb03d4b6604eb8d
Add `default_width/height` to loaded theme vars (replaces #1218 by a simpler solution)
https://github.com/leftwm/leftwm/blob/2eace8188a226ebace36b7ddabb03d4b6604eb8d/leftwm-core/src/state.rs#L181-L182
- 5debd321132ce0b18c5c486319be3b662b291837
Xlib Display Server `new()` now first loads the config into `Xwrap` and then calls `init()` without the config param.
https://github.com/leftwm/leftwm/blob/5debd321132ce0b18c5c486319be3b662b291837/display-servers/xlib-display-server/src/lib.rs#L38-L39
Split `load_colors()` into `load_config()` and …
> Refactor theme config loading

- display-servers/xlib-display-server/src/xwrap/setters.rs
Replace the complicated solution for setting the fourth byte by a simple OR operation.
> Simplify setting the fourth byte of a pixel to 0xff

- leftwm/src/bin/lefthk-worker.rs
- leftwm/src/config/keybind.rs
Fix builds without lefthk feature.
revert eaa13b3 and partially revert f78ed16 with minor edit.
> Fix build without lefthk

- leftwm/Cargo.toml
- leftwm/src/bin/lefthk-worker.rs
- leftwm/src/config/keybind.rs
Reverts leftwm/leftwm#1228
Uses @Eskaan's approach which prevents lefthk-worker from being built in the first place to resolve #1228.
> Revert "Fix build without lefthk"

- .github/workflows/ci.yml
- .github/workflows/docs.yml
- CONTRIBUTING.md
- leftwm/src/command.rs
I noticed that `cargo doc` failed due to a simple markup problem, so I fixed the markup. Then, I also attempted to add a CI workflow to generate crate docs (I cannot test this), and updated `CONTRIBUTING.md` to encourage other developers to render and view crate docs.
The errors are all the same cause at different locations, as exemplified here:
```
error: unclosed HTML tag `ScratchpadName`
--> leftwm/src/command.rs:21:15
|
21 |     /// Args: <ScratchpadName>
|               ^^^^^^^^^^^^^^^^
|
= note: `-D rustdoc::invalid-html-tags` implied by `-D warnings`
= help: to override `-D warnings` add `#[allow(rustdoc::invalid_html_tags)]`
```
I replaced angle brackets in all those cases with backticks:
```
`ScratchpadName`
```
-which is standard md markup to style as a code identifier: …
> `cargo doc` error fixes, CI workflow, and `CONTRIBUTING.md` update.

- Cargo.lock
- display-servers/xlib-display-server/Cargo.toml
- leftwm-core/Cargo.toml
- leftwm/Cargo.toml
This bumps mio to 0.8.11, resolving [CVE-2024-27308](https://github.com/advisories/GHSA-r8w9-5wcg-vfj7). LeftWM, specifically, does not appear to be vulnerable since 1) LeftWM uses Tokio 1.2.0 and 2) LeftWM does not natively target Windows.
Note: To fully reproduce CI checks, you will need to run `make test-full-nix`. Usually, this is not necessary
> chore: CVE-2024-27308 dependency update (mio)

- display-servers/x11rb-display-server/src/xwrap/window.rs
The X11 input hint wasn't correctly interpreted, causing dialogs and similar to not get input focus upon spawning (`never_focus` is set until un-focusing and focusing again, causing the window to get updated).
Fixes https://github.com/leftwm/leftwm/pull/1221#discussion_r1513520014 (see for more info on the bug)
> X11rb: Invert input hint

- leftwm/src/bin/leftwm-worker.rs
See title, for details see https://github.com/leftwm/leftwm/issues/1245#issuecomment-2040237340
(probably, can't reproduce) fixes #1245 
> X11rb: Fix sys-log by dropping boot-logger earlier

- leftwm-core/src/handlers/command_handler/scratchpad_handler.rs
- leftwm-core/src/models/scratchpad.rs
- leftwm-core/src/utils/child_process.rs
- leftwm/doc/leftwm.1
- leftwm/src/config/default.rs
This adds a new optional field for scratchpads that allows their child process to be called with arguments.
Fixes #1223
History of the art: #1216, #958.
> # Scratchpads
> 
> A scratchpad is a set of windows which you can call to any tag and hide it when not needed. These windows can be any set of application which can be run from a terminal. To call a scratchpad you will require a keybind for [ToggleScratchPad](#togglescratchpad). When you want to manipulate the currently focused scratchpad, other commands like [ReleaseScratchPad](#releasescratchpad), [AttachScratchPad](#attachscratchpad) and [NextScratchPadWindow/PrevScratchPadWindow](#nextscratchpadwindowprevscratchpadwindow) are available.
> 
> Example:
> 
> ```rust
> scratchpad: [
>     ( name: "Alacritty", // This is the name which …
```
> Add 'args' Scratchpad config entry

- leftwm-core/src/handlers/command_handler.rs
- leftwm-core/src/handlers/command_handler/scratchpad_handler.rs
- leftwm/src/bin/leftwm-log.rs
- leftwm/src/utils/log/file.rs
This resolves that latest clippy warnings, completing #1225.
> chore: latest clippies

- README.md
I've seen multiple people in the discord struggling with the backend feature flags, it should be more explicit now
> Updated README with backend build features flags

- examples/config-with-comments.ron
- leftwm-core/src/config/workspace_config.rs
- leftwm-core/src/models/screen.rs
- leftwm-core/src/models/workspace.rs
- leftwm/src/config.rs
- leftwm/src/config/default.rs
Fixes #1259 
This PR removes all references to the obsolete `max_window_width` variable from the codebase.
> chore: remove obsolete `max_window_width` variable 

- leftwm-core/src/utils/command_pipe.rs
Adds FocusWindow to command parsing, so it can be used with `leftwm-command`.
> Add missing match arm for FocusWindow command

- Cargo.lock
Update the `time` and `time-macros` crates in order to fix compilation error on Rust toolchain version 1.80
Fixes #1272 
`make test` fails, but this is unlikely to be due to the contents of this PR, since these errors are present without any modifications to the current `HEAD`.
- [] Ran `make test` locally with no errors or warnings reported
> Update time and time-macros

- display-servers/x11rb-display-server/src/event_translate.rs
This is fixing windows not being able to be moved and resized when the numlock is active under x11rb backend.
<sub>Just a very dum bug when you look at the code...</sub>
> x11rb: Fixed numlock preventing from moving and resizing floating windows

- CHANGELOG.md
- display-servers/x11rb-display-server/src/xwrap.rs
- display-servers/x11rb-display-server/src/xwrap/window.rs
- display-servers/xlib-display-server/src/xwrap.rs
- display-servers/xlib-display-server/src/xwrap/window.rs
- leftwm-core/src/config.rs
- leftwm-core/src/config/window_hiding_strategy.rs
- leftwm/src/config.rs
- leftwm/src/config/default.rs
Fixes #1100 by moving the window out of the screen rather than using `Map`/`Unmap` requests, which causes the window to appear black when captured when hidden
<sub>(clippy seems mad at some previous change....)</sub>
> Fix hiding window behaviour

- display-servers/x11rb-display-server/src/xwrap/window.rs
- display-servers/xlib-display-server/src/xwrap/window.rs
This makes some calls for the screens context when windows are hidden lazy. In particular this avoids some randr calls, which on some setups (when using nvidia prime for example) requires the dGPU to be awake: when it isn't, there is a noticeable latency. This avoids these lags as well as the unnecessary gpu wake up calls.
There may be a more in depth way to avoid these calls, but this removed the (quite frequently recurring) issue for me.
Note: To fully reproduce CI checks, you will need to run `make test-full-nix`. Usually, …
> Lazily call randr on windows hiding

- leftwm-core/src/models/dto.rs
This patch updates the behavior of the ```busy``` attribute. Previously, it would be set to ```true``` even if there were no windows in a workspace. With this patch, a workspace tag is considered ```busy``` only if the tag is both visible in that workspace and at least one window (excluding dock and desktop windows) has that tag.
Closes #787 
> Add distinction between visible and busy workspace

- display-servers/x11rb-display-server/src/xwrap/window.rs
- display-servers/xlib-display-server/src/xwrap/window.rs
- leftwm-core/src/models/window.rs
- leftwm/src/config.rs
In addition of #1274, this PR adds a new window rule parameter in case some window do not behave correctly under `MoveMinimize` or `MoveOnly` hiding behaviours, or if you want to be able to share specific windows but still have `Unmap` for other windows.
- `hiding_strategy` When specified, will force the window to hide in a certain way. See `window_hiding_strategy` for values.
> Implement window rule for `hiding_strategy`

- leftwm-core/src/handlers/window_handler.rs
This resolves several issues related to focusing.
The destroyed window is not removed from window history stack. Thus, on the next call `window_destroyed_handler()` tries to take the second window from windows history stack, but gets handler of already destroyed window, which is impossible to focus.
Fixes #1204, #1145
> fix: Remove destroyed window from history

- .github/workflows/release.yml
- CHANGELOG.md
- Cargo.lock
- display-servers/x11rb-display-server/Cargo.toml
- display-servers/x11rb-display-server/src/xatom.rs
- display-servers/xlib-display-server/Cargo.toml
- leftwm-core/Cargo.toml
- leftwm-macros/Cargo.toml
- leftwm-watchdog/Cargo.toml
- leftwm/Cargo.toml
Bumps dependency versions and leftwm versions to +0.0.1 (I did not skip 0.5.1 for the ones where we could...).
Fixes #1287 
> chore(v0.5.2): bump version, dependencies and prepare release for #1287

- CHANGELOG.md
- Cargo.lock
- display-servers/x11rb-display-server/Cargo.toml
- display-servers/xlib-display-server/Cargo.toml
- display-servers/xlib-display-server/src/xwrap/getters.rs
- leftwm-core/Cargo.toml
- leftwm-macros/Cargo.toml
- leftwm-watchdog/Cargo.toml
- leftwm/Cargo.toml
Fixes an issue in xlib-display-server where the slice width for 32 bit systems was assumed as 64 bits.
Releases 0.5.3.
Resolves #1291
> fix(xlib-display-server): resolve 32-bit width issue

- Cargo.lock
- display-servers/x11rb-display-server/src/error.rs
- display-servers/x11rb-display-server/src/event_translate.rs
- display-servers/xlib-display-server/src/event_translate.rs
- leftwm-core/Cargo.toml
- leftwm-core/src/handlers/command_handler.rs
- leftwm-core/src/handlers/command_handler/scratchpad_handler.rs
- leftwm-core/src/handlers/window_handler.rs
- leftwm-core/src/layouts/layout_manager.rs
- leftwm-core/src/models/tag.rs
- leftwm-core/src/state.rs
- leftwm-core/src/utils/modmask_lookup.rs
- leftwm-watchdog/Cargo.toml
- leftwm-watchdog/src/utils.rs
- leftwm/Cargo.toml
- leftwm/src/bin/leftwm-check.rs
- leftwm/src/bin/leftwm-log.rs
- leftwm/src/config.rs
- leftwm/src/utils/log/file.rs
- Bumps implicit dependencies for numerous crates and explicit ones for `thiserror` 
- Fixes numerous clippy errors present in recent builds
- Addresses warnings around conditional compilation for the benefit of package review.  
Fixes N/A
N/A
- N/A Manual page has been updated accordingly
- N/A Wiki pages have been updated accordingly (to perform **after** merge)
> chore: update dependencies, fix clippy errors, dismiss spurious warnings

- Cargo.lock
- flake.lock
- **update flake**
- **update cargo**
Update flake lock, as it is terribly outdated and pulls Rust 1.76 wich isn't in binary caches anymore, so it builds it from source
While at it, also update Cargo.lock, hoping this wont break things :angel:
not relevant
> chore: upate lock files

- leftwm-core/src/handlers/window_handler.rs
After a window closes, the focus is updated to another window. For sloppy focus this happens by queueing FocusWindowUnderCursor. However, when this action is being executed, there is a check for change in focus which happens _after_ the window being destroyed has been removed from the window history. This in turn causes us to think there is nothing to do and we exit early.
Push a None focus onto the window history to force an update. After all, we don't actually have anything in focus at the moment.
fixes #1295
Note: make test already fails for me on main. ~~I'll make a separate PR for that.~~ No actions required for the other two items.
> fix sloppy focus after window closes

- display-servers/x11rb-display-server/src/xwrap/window.rs
- display-servers/xlib-display-server/src/xwrap/window.rs
When switching tags back and forth in `ClickTo` focus, we can't click to focus any windows. Only after the windows have come into focus through other means, are we able to click on them.
So when switching tags, windows are hidden using the `OnlyMove` strategy. In this case these windows are left in the `Normal` window state, even if they aren't visible. When we switch back to the original tag, we then don't call `toggle_window_visibility`, because we think there's nothing to do. This in turn means we don't call `grab_mouse_events` on these windows, so we're never receiving any click events that enable us to click to focus.
So when marking windows invisible, always make sure we take them out of the 'normal' state.
Note: To fully reproduce CI checks, you will need to run `make …
> xlib, x11rb: fix ClickTo focus after switching tags

- display-servers/x11rb-display-server/src/lib.rs
- display-servers/xlib-display-server/src/lib.rs
Commit 4f765b4ba14 ('Various fixes') claims to 'make it work for non-sloppy focus' but in doing so, it breaks it for sloppy focus by forcing the focus to the root window. This doesn't seem to be the correct place to make this kind of decision anyway.
Removing this bit of code also doesn't really seem to break anything obvious on ClickTo or Driven focus, so we might as well get rid of it.
fixes #1108
> fix sloppy focus with margins

- leftwm-core/src/config/workspace_config.rs
- leftwm-core/src/layouts/layout_manager.rs
- leftwm-core/src/models/manager.rs
- leftwm/doc/leftwm.1
Implements the feature discussed in #1296, allowing you to set a "default layout" for a workspace, and implementing corresponding layout management logic
Non-breaking since the `default_layout` field is annotated with the `#[serde(default)]` macro, so will just be set to `None` if not given
Note: I haven't actually ran this locally to ensure it actually works, but the tests pass.
Fixes #1296
There currently isn't documentation for the `layouts` field of a workspace, so that should probably be added too, but just for this feature it could look like adding
"""
Example (setting the default layout of workspace 1 to `Monocle`):
```ron
workspaces: [
( output: "HDMI-1", y: 0, x: 0, height: 1440, width: 1720, default_layout: "Monocle"),
]
```
"""
somewhere in …
> feat(#1296): add default_layout option to config

- display-servers/x11rb-display-server/src/xwrap/getters.rs
On x11rb, scratchpad windows are handled like any normal window: the window doesn't float in the designated area, and is just added to the active tag's window stack. This is because the WindowCreate event doesn't receive a usable pid and due to that, the window can't be matched up to any of the active scratchpads.
This all happens because `xwrap::get_property` calls `xproto::get_property` with `0` as the last argument, which effectively tells it to return no items.
So set it to `1` instead.
fixes #1294
> fix creating a scratchpad window on x11rb

- display-servers/x11rb-display-server/src/xwrap/window.rs
When opening a dialog in a Qt application like wireshark, the dialog isn't mapped due to the fact that the window doesn't have a legacy name. In the case of wireshark, this blocks further use of the application.
We store the legacy name in an `Option`, so we should be able to deal with it being `None`. Translate any errors when fetching the legacy name into it just not being available, pretty much like the xlib backend does.
Fixes #1317 
> x11rb: allow legacy name to not exist

- display-servers/x11rb-display-server/src/xwrap/getters.rs
Getting the output name always fails, as indicated by the `FIX` note, leading to leftwm-state to always say the current output is `"output_name"`.
This happens because we're assuming we're still doing ffi here and as such are trying to read a null-terminated string from some bytes. In fact the data isn't null-terminated, at least not here. And since there is no null-termination, the conversion always fails.
To get this to work, we can simply convert the data to `str` and drop the whole `CStr` use.
> x11rb: getters: fix getting the output name

- leftwm-core/src/handlers/command_handler/scratchpad_handler.rs
Remove the try_bool macro definition and use and replace it with a let-else construction. I'm presuming the macro setup was written before 1.65, when let-else wasn't available yet. We can now reduce the implementation to about half the number of lines.
> scratchpad_handler: remove try_bool macro

- README.md
This updates the url for the xmobar repo in the README.md to codeberg as the github repo isn't existing anymore. Also see issue.
Fixes #1327
> update xmobar source url in README

- leftwm/src/config.rs
This small change enhances the warning message when a submitted path does not exist by including the actual path value.
> fix: include path in warning when path does not exists

- leftwm/src/config.rs
SerializableRegex allows to serialize Regex without using a reference to an option. This will avoid the clippy warning about ref_option.
Fixes #(1307)
- [x ] Ran `make test` locally with no errors or warnings reported
> config: Add SerializableRegex to serialize Regex (#1307)

- CHANGELOG.md
- Cargo.lock
- README.md
- leftwm/Cargo.toml
- leftwm/doc/leftwm.1
- leftwm/src/bin/leftwm-check.rs
- leftwm/src/command.rs
- leftwm/src/config.rs
- leftwm/src/theme_config.rs
Previously, as part of 0.4.0, we deprecated TOML so we could use RON. This change removes TOML support entirely, relying on external binary [`leftwm-config`](https://github.com/leftwm/leftwm-config/tree/main) to handle migrations going forward. Any users who have not migrated to RON from TOML will need to do so using `leftwm-config` or manual updates.
We will need to check that `leftwm-theme` and `leftwm-config` are prepared to take on this change as well.
Fixes: #875
All references to `-m, --migrate-to-ron` should instead reference `leftwm-config`. 
Note: To fully reproduce CI checks, you will …
> feat!(config): Remove TOML support (implement #875) BREAKING CHANGE
