leftwm/leftwm

src/command_builder.rs, src/config.rs, src/display_servers/xlib_display_server/xwrap.rs, src/handlers/command_handler.rs, src/handlers/display_event_handler.rs, src/handlers/focus_handler.rs, src/handlers/mouse_combo_handler.rs, src/handlers/window_handler.rs, src/handlers/window_move_handler.rs, src/handlers/window_resize_handler.rs, src/lib.rs, src/models/manager.rs, src/models/window.rs, src/models/window_change.rs, src/models/workspace.rs, src/models/xyhw.rs, src/utils/child_process.rs, src/utils/command_pipe.rs, src/utils/helpers.rs, src/utils/state_socket.rs, src/utils/xkeysym_lookup.rs
There were only two I couldn't fix.  I had to put clippy ignores in these cases.  The line below is what I needed to ignore the issues.
#[allow(clippy::cast_lossless, clippy::cast_ptr_alignment)]
=> Running Clippy and fixing all errors

src/config/loader.rs, src/config/theme_setting.rs, src/display_servers/mock_display_server.rs, src/display_servers/mod.rs, src/display_servers/xlib_display_server/event_translate.rs, src/display_servers/xlib_display_server/event_translate_map_request.rs, src/display_servers/xlib_display_server/event_translate_property_notify.rs, src/display_servers/xlib_display_server/mod.rs, src/display_servers/xlib_display_server/xwrap.rs, src/handlers/command_handler.rs, src/utils/child_process.rs
Take a look at the command handler to see what approach you like
NOTE:  It compiles, but I didn't run it yet.   All changes should be fine.
=> Refactoring some code.

src/display_servers/xlib_display_server/xwrap.rs, src/handlers/goto_tag_handler.rs, src/models/dto.rs, src/models/window.rs, src/models/workspace.rs, src/utils/window_updater.rs, themes/basic_lemonbar/template.liquid, themes/basic_polybar/template.liquid, themes/basic_xmobar/template.liquid
I fixed a misspelling in the code base ("visable" => "visible"). I tested that the project compiles, and it seems to work as it did before but admittedly I have done very little testing. 
Is this likely to break compatibility with prior themes or something similar?
=> replaced all occurrences of visable with visible

src/layouts/mod.rs
Works up to 6 windows as tested with the basic_polybar theme.
=> Implemented Fibonacci layout and added to available tiling methods.

src/layouts/mod.rs, src/models/dto.rs, src/models/workspace.rs
It can be useful for example if one (like myself) wants to show current layout in the status bar.
=> Add current layout to leftwm-state output

src/layouts/mod.rs
I have a super ultrawide monitor (5120x1440) where the splitting down the center has one looking far left or right at the primary window. By centering the primary window splitting the remaining windows left and right a nice balance is experienced.
=> feat(layout) center main

README.md
... for those who have no clue (like me)
=> link to EWMH wiki page

README.md, src/command.rs, src/handlers/command_handler.rs, src/handlers/external_command_handler.rs, src/utils/command_pipe.rs
=> Add FocusNextTag FocusPreviousTag, as per leftwm/leftwm#114

src/models/mod.rs, src/models/window.rs, src/models/workspace.rs
It's cleaner than String.
This commit has not covered all the replacement. 
If necessary, I will replace all later
=> new Type Tag

src/config/theme_setting.rs
It is possible to use [container attributes](https://serde.rs/container-attrs.html#default) and use `default` implementation for missing fields. Also it turns out that we have to rename `on_new_window_cmd` field to remain backward compatible. Should we keep it as-is or simply rename field to `on_new_window`?
=> Serialize/deserialize `ThemeSetting` directly

README.md, src/models/window.rs, src/models/workspace.rs
I *believe* the title says it all!
=> Fix typos, grammar, and consistency in README, plus rustfmt

.github/workflows/ci.yml, src/bin/leftwm-state.rs, src/bin/leftwm-worker.rs, src/bin/leftwm.rs, src/config.rs, src/display_action.rs, src/display_event.rs, src/display_servers/xlib_display_server/event_translate.rs, src/display_servers/xlib_display_server/event_translate_client_message.rs, src/display_servers/xlib_display_server/event_translate_property_notify.rs, src/display_servers/xlib_display_server/mod.rs, src/display_servers/xlib_display_server/xwrap.rs, src/handlers/command_handler.rs, src/handlers/focus_handler.rs, src/handlers/mouse_combo_handler.rs, src/handlers/window_move_handler.rs, src/handlers/window_resize_handler.rs, src/layouts/fibonacci.rs, src/layouts/mod.rs, src/models/dto.rs, src/models/window_change.rs, src/models/workspace.rs, src/models/xyhw_change.rs, src/state.rs, src/utils/child_process.rs
=> Build and run tests using GitHub Actions

.github/workflows/ci.yml
Triggers the workflow on push or pull request events but only for the master branch.
=> Run workflow only for push and pull request to master branch

Cargo.toml, src/bin/leftwm-state.rs, src/bin/leftwm-worker.rs, src/display_servers/xlib_display_server/event_translate.rs, src/display_servers/xlib_display_server/mod.rs, src/display_servers/xlib_display_server/xwrap.rs, src/layouts/center_main.rs, src/models/window.rs, src/utils/command_pipe.rs, src/utils/helpers.rs, src/utils/state_socket.rs
=> Upgrade tokio and futures dependencies.

src/display_servers/xlib_display_server/xwrap.rs
=> Continue polling xlib socket after an error

src/utils/child_process.rs
Howdy,
This PR enables support for X-GNOME-Autostart-enabled, which should close #82. It will only not run if false, it will otherwise run if true, any other value, or not set.
Best,
Mautamu
=> Obey X-Gnome-Autostart Closes #82

src/bin/leftwm-check.rs, src/bin/leftwm-state.rs, src/bin/leftwm-worker.rs, src/handlers/window_move_handler.rs, src/models/dto.rs, src/models/mod.rs, src/models/xyhw_change.rs, src/state.rs, src/utils/child_process.rs, src/utils/command_pipe.rs, src/utils/helpers.rs, src/utils/mod.rs, src/utils/state_socket.rs, src/utils/xkeysym_lookup.rs
Howdy,
This PR will make restore slightly more performant by using an iterator rather than a for loop.
Best,
Mautamu
=> Improve restore and apply some pedantic lints

src/layouts/center_main.rs, src/layouts/center_main_balanced.rs, src/layouts/even_horizontal.rs, src/layouts/even_vertical.rs, src/layouts/fibonacci.rs, src/layouts/grid_horizontal.rs, src/layouts/main_and_deck.rs, src/layouts/main_and_horizontal_stack.rs, src/layouts/main_and_vert_stack.rs, src/layouts/mod.rs, src/layouts/monocle.rs, src/layouts/right_main_and_vert_stack.rs, src/models/workspace.rs, src/utils/window_updater.rs
There is still one the resides in center_main_balanced with the fibonacci function. Had to alter a test and remove the filter, as this created a &mut &mut, and the test requires that the window is altered in-place to be able check the height and width. Closes #271.
=> Remove most mut mut

src/handlers/command_handler.rs, src/handlers/external_command_handler.rs, src/handlers/window_handler.rs, src/handlers/window_move_handler.rs
Some minor clippy fixes caused by recent pr's.
=> minor clippy fixes

src/handlers/window_handler.rs
Its not an ideal solution (inserting at the front of vec is slow), but works. Closes #238 and closes #277 hopefully.
=> Insert new dialogs and splashes on top

src/handlers/command_handler.rs
As requested in #269, the deck will cycle when main has focus.
Thanks.
=> cycle the deck when main has focus

Cargo.lock, src/utils/command_pipe.rs
Howdy,
This PR adds code I had stashed, closes #289. Should probably double check that all commands were added and that this works (I don't usually use external commands).
Best,
Mautamu
=> Refactor external command parsing

src/config.rs
Howdy,
This PR adds a few terminals to the list of checked terminals (kitty, xfce4, konsole, uxterm, guake). It also adds an `exit_strategy()` function that determines whether to exit using `loginctl kill-session XDG_SESSION_ID` or `pkill leftwm` as per #288. Closes #288 
Best,
Mautamu
=> Changes default mod+shift+x keybind, closes #288

src/command.rs, src/display_action.rs, src/display_servers/xlib_display_server/mod.rs, src/display_servers/xlib_display_server/xwrap.rs, src/handlers/command_handler.rs, src/handlers/external_command_handler.rs, src/models/window.rs, src/models/workspace.rs, src/utils/command_pipe.rs, src/utils/window_updater.rs
Adds a keybind command and logic to full screen any window, and update the the window state.<del> I just need to add an external command. </del> Closes #174 (and closes #170 in case this gets merged before #301).
Thanks.
=> Toggle fullscreen

src/layouts/main_and_deck.rs, src/layouts/main_and_vert_stack.rs, src/layouts/right_main_and_vert_stack.rs
Fixed the logic in relevant  layouts when being flipped, Closes #303. Let me know if I missed any.
Thanks.
=> Fix layouts when being flipped

src/handlers/command_handler.rs, src/handlers/display_event_handler.rs, src/handlers/external_command_handler.rs, src/handlers/focus_handler.rs, src/handlers/goto_tag_handler.rs, src/handlers/mouse_combo_handler.rs, src/handlers/window_handler.rs, src/handlers/window_move_handler.rs, src/handlers/window_resize_handler.rs, src/models/tag.rs, src/models/window.rs, src/models/workspace.rs, src/utils/helpers.rs
This is mainly a cleanup and refactor to make the code more consistent and readable. The only logical changes are around increase/decrease_main_width where I generalised the function called and the logic to the tag.
Even though I didn't really change any logic, this should still be properly tested in case I have missed something.
Thanks.
=> Cleanup in mostly handlers

src/models/workspace.rs
This removes unneeded work and also prevents an issue for monocle and main_and_deck where windows would be set visible behind a fullscreen window.
Thanks.
=> Don't update other windows when in fullscreen

src/display_servers/xlib_display_server/xwrap.rs
As mentioned in #313. Should also close #313.
Thanks.
=> Force border opacity to 100%

.github/ISSUE_TEMPLATE/bug_report.md, Cargo.lock, Cargo.toml, src/bin/leftwm-check.rs
Howdy,
As mentioned in #317, we might consider adding issue templates. This complements #321 by @AethanFoot.
Best,
Mautamu
=> Add issue template

src/bin/leftwm-state.rs
Add option for leftwm-state to use template liquid with a string literal instead of a `template.liquid` file.
This allows for very simple output for testing and scripting without the need to use a tempalte-file.
For now I did just a lazy initial implementation to get some opinions, without handling the strings nicely with quotes.
So for now only very rudimentary use like
```sh
leftwm-state -s {{ window_title }} -w 0
leftwm-state -w 0 -s {{ workspace.tags }} -q
```
is possible. But if the idea is welcome, I'll dive into supporting full inline liquid strings
=> `leftwm-state` option to use template string instead of template file

themes/basic_lemonbar/change_to_tag, themes/basic_polybar/change_to_tag, themes/basic_xmobar/change_to_tag, themes/controlling_leftwm/change_to_tag, themes/controlling_leftwm/move_window_to_last_workspace, themes/controlling_leftwm/move_window_to_tag, themes/controlling_leftwm/swap_screens
Just a minor update to reflect the inclusion of the `leftwm-command`.
=> Update change_to_tag to use leftwm-command.

src/handlers/command_handler.rs
Closes #342.
Thanks.
Edit not complete.
=> WIP: Fix #342

src/bin/leftwm-worker.rs, src/config.rs, src/display_action.rs, src/display_servers/xlib_display_server/event_translate.rs, src/display_servers/xlib_display_server/mod.rs, src/display_servers/xlib_display_server/xwrap.rs, src/handlers/command_handler.rs, src/handlers/display_event_handler.rs, src/handlers/external_command_handler.rs, src/handlers/focus_handler.rs, src/handlers/goto_tag_handler.rs, src/handlers/mouse_combo_handler.rs, src/handlers/screen_create_handler.rs, src/handlers/window_handler.rs, src/models/focus_manager.rs, src/models/manager.rs, src/models/mod.rs, src/models/workspace.rs
This is a start on #326. So far the basic model is set up with all previous functionality, I have the click replay working for click to focus (currently all processed clicks replay which will change). I need to implement the things from #350, and try and clean up areas where focus comes up. I will also remove moving the pointer when focus isn't sloppy. 
If anyone has any opinions please share. I will be continuing this tomorrow hopefully.
Thanks.
=> Focus manager

src/bin/leftwm-worker.rs, src/bin/leftwm.rs, src/utils/child_process.rs
This implements the change proposed in #362.
Closes #362.
=> Global up script

src/display_servers/xlib_display_server/event_translate.rs, src/display_servers/xlib_display_server/event_translate_property_notify.rs, src/display_servers/xlib_display_server/xwrap.rs, src/handlers/window_handler.rs, src/models/dock_area.rs, src/models/screen.rs
This will fix #380 and fix #229. Currently have fixed and tested when the bar is in any combination of top/bottom, when monitors are stacked. Any testing anyone has time for will be greatly appreciated, hopefully this will be fully running by tomorrow (if I have time).
Tahnks!
=> Fix #380 & #229. Testing Requested.

src/handlers/command_handler.rs, src/handlers/window_handler.rs, src/models/window.rs
Fixes #383 and implements the suggested mechanics.
Thanks.
=> Fix and implement #383

src/display_event.rs, src/display_servers/xlib_display_server/event_translate_client_message.rs, src/display_servers/xlib_display_server/xwrap.rs, src/models/dock_area.rs, src/models/manager.rs
This allow leftwm to compile on 32 bit architectures in response to #389 and #404. Hopefully this works (I can only test with i686-unknown-linux-gnu). If arm builds are still failing the solutions I have found (but can't test) is to make sure the correct linker is set (I would of thought it is when being built on that given architecture), these are at https://github.com/rust-lang/rust/issues/28924.
Thanks.
=> Support 32bit archs

src/display_servers/xlib_display_server/xwrap.rs, src/handlers/command_handler.rs, src/handlers/window_handler.rs
Fixes #407. Just makes sure the current scratchpad is on top, also added a gate to stop us trying to move the cursor of screen.
Thanks.
=> Implement 407

src/handlers/command_handler.rs, src/handlers/focus_handler.rs, src/handlers/goto_tag_handler.rs, src/handlers/window_handler.rs, src/models/focus_manager.rs
Resolves #352 and resolves #353. #353 wasn't easily achievable for focus goes to the next window in the stack (Generally takes the place of the moved/closed window), as backup we then checked for the previous window in the stack.
Thanks.
=> Focus changes

src/bin/leftwm-worker.rs, src/handlers/command_handler.rs, src/handlers/screen_create_handler.rs, src/layouts/center_main.rs, src/layouts/center_main_balanced.rs, src/layouts/fibonacci.rs, src/layouts/main_and_deck.rs, src/layouts/main_and_horizontal_stack.rs, src/layouts/main_and_vert_stack.rs, src/layouts/mod.rs, src/layouts/right_main_and_vert_stack.rs, src/models/mod.rs, src/models/tag.rs, src/models/workspace.rs, src/utils/window_updater.rs
Initial refactor of tag, there will probably other bits around this that I will change. This fixes #437 in this, with the solution being to add a hidden flag to a tag (which will be on by default for the scratchpad tag) as it may be useful to have a general way to hide a tag rather then a specific method for just the scratchpad tag.
Thanks!
=> Refactor tag to remove needless arc

src/layouts/main_and_horizontal_stack.rs, src/layouts/main_and_vert_stack.rs
This is a minor documentation fix but it had me confused for a while.
=> Update documentation for layouts

Cargo.lock, Cargo.toml
Howdy,
This PR updates `liquid` to 0.23
=> Update liquid to 0.23

src/bin/common/config.rs, src/command_builder.rs, src/display_servers/mock_display_server.rs, src/display_servers/xlib_display_server/xatom.rs, src/display_servers/xlib_display_server/xcursor.rs, src/display_servers/xlib_display_server/xwrap.rs, src/errors.rs, src/handlers/command_handler.rs, src/layouts/main_and_deck.rs, src/layouts/main_and_vert_stack.rs, src/layouts/mod.rs, src/models/dock_area.rs, src/models/focus_manager.rs, src/models/gutter.rs, src/models/manager.rs, src/models/screen.rs, src/models/tag.rs, src/models/window.rs, src/models/window_change.rs, src/models/workspace.rs, src/models/xyhw.rs, src/models/xyhw_change.rs, src/utils/child_process.rs
Howdy,
This PR updates several files to prepare for the coming clippy train branching.
Best,
Mautamu
=> Apply clippy lints (CV > 1.56.0) and documentation improvements.

README.md
Closes #27, closes #137.
Howdy,
This PR closes out a few older issues:
- #27: LeftWM-theme now exists
- #103: This one *might* not be fully addressed, so I'll leave it for now
- #137: Resolved by #269 
As requested in #482, #160, #27, #452, I have created a community Discord. Added that to the README, as well as bumping the Wiki version to 0.2.8. Would be more than happy to give you Discord ownership, @lex148. Just thought we might as well make one.
Best,
Mautamu
=> Add Discord link. Clean up a few other old issues;

src/handlers/window_handler.rs
=> Make scratchpad size to the setting consistently

Cargo.lock, Cargo.toml, src/bin/common/config.rs
Hopefully fixes theme paths that include spaces, as discussed on the discord.
Thanks
=> fix theme paths with spaces

src/bin/leftwm.rs, src/utils/child_process.rs
=> fix autostart

themes/basic_eww/change_to_tag, themes/basic_eww/eww-bar/eww.yuck, themes/basic_eww/template.liquid
Hi everyone,
I've recently changed to `leftwm + eww-bar`. The basic-eww theme was somehow not working then clicking on the workspace section of the bar so adjusted the command that runs there.
Please let me know whether I can improve anything and I'll do it asap!
=> Fixed the command for basic-eww theme on workspace change

leftwm-core/src/handlers/window_handler.rs
on_same_tag should start true.
=> Correct bool

README.md
As mentioned in #533 (though adding stuff, instead of making the REAME.md lighter :joy:)﻿
=> README: Add info about Makefile

CHANGELOG, CONTRIBUTING.md, Cargo.lock, README.md, leftwm-core/Cargo.toml, leftwm/Cargo.toml, leftwm/src/command.rs, leftwm/src/config.rs
Howdy,
This PR does the following:
CHANGELOG/README
* Updated MSRV to 1.52.0, as it is latest version that compiles LeftWM for me.
* Cleaned up some grammar/spelling
leftwm/Cargo.toml and leftwm-core/Cargo.toml
* Updated mio, nix to latest versions
* Pinned thiserror and anyhow to latest to avoid supply-side attacks
* Formatted toml files with dprint
Cheers,
Mautamu
=> Maintenance (*): Update dependencies, clean up code, new lints.

README.md
=> fix dependencies in README.md

leftwm-core/src/display_servers/xlib_display_server/xwrap/mod.rs, leftwm-core/src/handlers/command_handler.rs, leftwm-core/src/handlers/window_move_handler.rs
@VuiMuich I am sneaking another one in :wink:. This further improves #517. Also fixes the problem you mentioned in discord.
=> Better 517, and fix floating windows being behind

leftwm-core/src/handlers/window_handler.rs
Pushes the min version back to 1.52.
=> Version fix

CHANGELOG, leftwm-core/Cargo.toml, leftwm/Cargo.toml
=> Version bump

.gitignore, leftwm-core/src/display_servers/xlib_display_server/event_translate.rs, leftwm-core/src/handlers/command_handler.rs
fixed fix RightWiderLeftStack and LeftWiderRightStack not having the right width and an issue where Leftwm would refuse to start when running under Xephyer cause of a devide by zero error...
=> fix fix RightWiderLeftStack and LeftWiderRightStack not having the right … 

CHANGELOG, leftwm-core/Cargo.toml, leftwm/Cargo.toml
As discussed on discord, bringing the versioning more inline with semantic versioning.
=> Version Rejig

.github/workflows/ci.yml
This updates the GH Actions script to also run on pull/commit for the `v0.2.x` branch
=> GitHub Actions (ci.yml): Update to run on `v0.2.x`

README.md, leftwm-core/src/config/mod.rs, leftwm-core/src/config/workspace_config.rs, leftwm-core/src/handlers/command_handler.rs, leftwm-core/src/handlers/screen_create_handler.rs, leftwm-core/src/layouts/mod.rs, leftwm-core/src/models/layout_manager.rs, leftwm-core/src/models/manager.rs, leftwm-core/src/state.rs
This is an attempt to resolve #618, this is still WIP, but thought I would open the PR for early feedbacks before proceeding. It's still untested and I'm not sure how it will work with `layout_mode`
=> Implement layouts per workspace

leftwm-core/src/command.rs, leftwm-core/src/display_event.rs, leftwm-core/src/display_servers/xlib_display_server/event_translate.rs, leftwm-core/src/display_servers/xlib_display_server/event_translate_client_message.rs, leftwm-core/src/handlers/command_handler.rs, leftwm-core/src/handlers/display_event_handler.rs, leftwm-core/src/handlers/focus_handler.rs, leftwm-core/src/models/window.rs, leftwm-core/src/state.rs, leftwm-core/src/utils/command_pipe.rs, leftwm-core/src/utils/state_socket.rs, leftwm/src/config/mod.rs
Fixes #650, fixes #637, restore window tag on reload, and clippy bits.
Thanks!
=> Various fixes

leftwm/src/config/checks.rs, leftwm/src/config/keybind.rs
Simplifies the check in `check_mousekey` considerably
=> Add `Modifier::is_empty`, use it in `check_mousekey`

leftwm-core/src/display_event.rs, leftwm-core/src/display_servers/xlib_display_server/event_translate.rs, leftwm-core/src/handlers/display_event_handler.rs, leftwm-core/src/handlers/mouse_combo_handler.rs
=> fix(416): focus empty workspace on click

Cargo.lock, leftwm/Cargo.toml, leftwm/src/bin/leftwm-state.rs, leftwm/src/bin/leftwm-worker.rs
Hello,
@bmclean2, @franLMSP, @VentGrey would y'all mind testing this? One of the best stress tests I found is to get CPU usage in the 90%+ range with at least one browser open and a terminal window compiling something (approaching 100% RAM utilization also).
If accepted, fixes #275, fixes #575; supersedes/closes #697.
Best,
Mau
=> Attempt to fix #275, #575; if accepted, supersedes #697

leftwm-core/src/config/insert_behavior.rs, leftwm-core/src/config/mod.rs, leftwm-core/src/handlers/window_handler.rs, leftwm-core/src/state.rs, leftwm/src/bin/leftwm-check.rs, leftwm/src/bin/leftwm-state.rs, leftwm/src/config/default.rs, leftwm/src/config/mod.rs
This implements #358 and allows configurable behavior for new windows.
=> Configurable new window behavior

leftwm-core/src/command.rs, leftwm-core/src/handlers/command_handler.rs, leftwm-core/src/utils/command_pipe.rs, leftwm/src/command.rs, leftwm/src/config/keybind.rs
* Initial implementation of CloseAllOtherWindows command
* Given a window, close all other windows in the workspace
=> CloseAllOtherWindows command

CONTRIBUTING.md
=> Add wiki pages to update after PR in CONTRIBUTING.md

Cargo.lock, leftwm-core/src/event_loop.rs, leftwm-core/src/utils/child_process.rs, leftwm/Cargo.toml, leftwm/src/bin/leftwm.rs
I refactored the `leftwm.rs` which should make it easier to read now (at least in my opinion).
Fixes #(issue)
No reason to update them.
=> Refactor leftwm main

leftwm-core/src/display_event.rs, leftwm-core/src/display_servers/xlib_display_server/mod.rs, leftwm-core/src/event_loop.rs, leftwm-core/src/utils/state_socket.rs, leftwm/src/bin/leftwm-worker.rs, leftwm/src/bin/leftwm.rs, leftwm/src/config/mod.rs, rust-toolchain.toml
Just a little refactoring to the event loop.
Fixes #(issue) None
None
=> Event loop refactor

.github/workflows/new-issues.yml
**Description**
Adds a workflow that automatically adds all new issues and PRs to the roadmap project board.
=> add new-issues workflow

README.md
=> Add lefthk-worker to README

README.md
Just update readme to match the latest merges.
=> Update readme bkp

.github/workflows/ci.yml
- bump MSRV to 1.57.0
- bump MSRV to 1.59.0 for crate `time v0.3.14`
Fixes #(issue)
=> bump MSRV to 1.59.0 for crate `time` v0.3.14

flake.nix
=> Remove libxcb

README.md
=> Improve `startx` section in README

Makefile
=> update makefile for `lefthk-worker`

leftwm-core/src/handlers/window_handler.rs
=> making centering working again

leftwm/src/config/keybind.rs, leftwm/src/config/mod.rs
I just stepped over this while looking at the window creation in leftwm.
The score computation was a bit hard to understand so I splitted it into vars to
make it easier to understand the steps/calculation of the score.
Not needed
=> refactor score window function

.github/pull_request_template.md
=> Added a few options to the pr template

leftwm/src/config/checks.rs
=> Improve output of `leftwm-check --verbose`

leftwm/src/bin/leftwm-check.rs
=> Fix a clippy warning

leftwm/src/bin/leftwm-check.rs, leftwm/src/bin/leftwm-command.rs, leftwm/src/bin/leftwm-state.rs, leftwm/src/bin/leftwm.rs
Bugfix and refactored some stuff
Fixes #933
Not needed
=> better clap and fix broken `workspace` flag for `leftwm-state`

leftwm/build.rs, leftwm/src/bin/leftwm-check.rs
add features log to leftwm-check - draft.
=> add features log to leftwm-check.

leftwm/src/bin/leftwm-check.rs
add lefthk feature check to leftwm-check, and error reporting.
=> added lefthk feature checks and errors

leftwm/src/config/default.rs
=> Change default layout mode to `Tag`

display-servers/xlib-display-server/src/lib.rs, leftwm-core/src/handlers/window_handler.rs, leftwm-core/src/layouts/center_main_balanced.rs, leftwm-core/src/layouts/fibonacci.rs, leftwm-core/src/layouts/main_and_deck.rs, leftwm-core/src/layouts/main_and_horizontal_stack.rs, leftwm-core/src/layouts/main_and_vert_stack.rs, leftwm-core/src/models/tag.rs, leftwm-core/src/utils/command_pipe.rs, leftwm/build.rs, leftwm/src/bin/leftwm-check.rs, leftwm/src/bin/leftwm-command.rs, leftwm/src/bin/leftwm-state.rs, leftwm/src/bin/leftwm.rs, leftwm/src/command.rs, leftwm/src/config/checks.rs, leftwm/src/config/keybind.rs, leftwm/src/config/mod.rs
Simply apply the changes clippy suggests when running `make test-full`, which could be done mostly automatically.
=> Apply changes suggested by clippy trough `make test-full`

CHANGELOG, README.md, display-servers/xlib-display-server/Cargo.toml, leftwm-core/Cargo.toml, leftwm/Cargo.toml
- bump readme and cargo.toml files to 0.4.1
- update changelog
=> release `0.4.1`

Cargo.lock
Push Cargo.lock with the latest release bumps.
=> push Cargo.lock

leftwm-core/src/utils/child_process.rs
Remove field codes from Exec string when autostarting apps.
Fixes #1061
Before:
After:
=> Remove field codes from Exec string when autostarting apps

leftwm/src/bin/leftwm-check.rs
This commit adds an additional check to `leftwm-check`: `check_binaries`. This is similar in nature to `leftwm-check::check_feature_dependencies`, but also checks for `leftwm`, `leftwm-state`, `leftwm-command`, `leftwm-worker`, and `leftwm-check` to ensure that all leftwm-required binaries exist in the user's current PATH variable.
To update [Troubleshooting](https://github.com/leftwm/leftwm/wiki/Troubleshooting):
| Issue | Description | Solution |
|-|-|:-:|
| No config.ron file exists | LeftWM does not always ship with a `config.ron`. You will need to execute LeftWM at least once for one to be generated. | Try the following: ``` leftwm-worker ``` |
| Config.ron is not being parsed | LeftWM ships with a binary called leftwm-check. It might not be installed by the AUR. | Try the following: …
=> feat(leftwm-check): Add a check for other binaries to leftwm-check

CHANGELOG, Cargo.lock, README.md, display-servers/xlib-display-server/Cargo.toml, leftwm-core/Cargo.toml, leftwm/Cargo.toml
Preparing the next version bump to 0.4.2
=> prepare 0.4.2 release

leftwm-core/src/event_loop.rs, leftwm-core/src/handlers/command_handler.rs, leftwm-core/src/handlers/command_handler/scratchpad_handler.rs, leftwm-core/src/handlers/window_handler.rs, leftwm-core/src/utils/child_process.rs, leftwm-core/src/utils/return_pipe.rs, leftwm/src/bin/leftwm-state.rs
This PR:
- addresses Clippy lints
- adds an empty rustfmt.toml file (see the associated commit message)
=> Minor improvements : clippy & rustfmt

Cargo.lock, display-servers/xlib-display-server/src/xwrap/getters.rs, display-servers/xlib-display-server/src/xwrap/setters.rs, leftwm-core/Cargo.toml, leftwm/Cargo.toml, leftwm/src/bin/lefthk-worker.rs, leftwm/src/bin/leftwm-check.rs, leftwm/src/bin/leftwm-command.rs, leftwm/src/utils/log.rs
- Updates deps to latest
- Updates lints to 0.1.73
=> chore: Clippy lints, upgrade dependencies

examples/config-with-comments.ron
This is an extension of https://github.com/leftwm/leftwm/pull/1152#issuecomment-1773806736 to update documentation.
=> chore: Add create_follows_cursor, 1152, to config.ron example

leftwm-core/src/handlers/window_handler.rs, leftwm-core/src/models/tag.rs, leftwm-core/src/state.rs
Some performance and grammar nitpicks I stumbled upon, see code for details.
=> Misc optimizations / corrections

leftwm-core/src/handlers/display_event_handler.rs
Moving the center of floating windows over the edge of the workspace would move them to the first tag whilst a big part of the window was still visible.
Like the old code, the new first checks the center of the window in case the window overlaps multiple workspaces but then also tries to find any intersecting workspace.
Fixes #1054
=> Fix moved windows switching to the first tag

leftwm/build.rs
Fixes typos in the build.rs file.
=> Add spelling fixes for lefthk setup notice

.github/workflows/release.yml, leftwm-macros/README.md
Corrects issues we had with the release by adding a README and changing the release order.
Fixes #(issue)
=> chore: Release 0.5.0 with minor release fixes

.github/workflows/release.yml
Went ahead and manually corrected the 0.5.0 release, but this should fix the issue for releasing going forward.
=> chore: Fix typo

leftwm/src/bin/leftwm-command.rs
=> Some formatting chores

display-servers/xlib-display-server/src/xwrap/setters.rs, leftwm/src/bin/leftwm-log.rs
Resolves the latest clippy warnings which have begun to appear on builds.
=> chore: latest clippies

.github/workflows/ci.yml, CHANGELOG.md, Cargo.lock, README.md, flake.lock, leftwm-core/Cargo.toml, leftwm-macros/Cargo.toml, leftwm-watchdog/Cargo.toml, leftwm/Cargo.toml
Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change. This is needed to update clap to ^4.5, which depends on rust >= 1.74.0.
Wiki needs MSRV updated from 1.70.0 to 1.74.0; README and CHANGELOG have been updated within this PR.
=> chore: update MSRV to 1.74, update dependencies

.github/workflows/codeberg-mirror.yml
This PR updated the 1195-testing branch with the latest mirroring code to test #1195.
Sets up test for #1195
N/A; infra update
N/A; infra update
N/A; infra update
=> test(PR#1195): Fix mirror ci

themes/basic_xmobar/template.liquid
I' ve added comments to the template.liquid file.
Now is better usable
I've also made some additions , with showing the leftwm layout and the focused window title.
=> Commented template.liquid

README.md
fixes a dead link in the project README related to the default layouts 
Fixes #1299
None that I'm aware of
NA
=> chore: fix dead link in readme

.github/workflows/run-tests.yml, display-servers/x11rb-display-server/src/lib.rs, display-servers/x11rb-display-server/src/xwrap.rs, display-servers/x11rb-display-server/src/xwrap/window.rs, display-servers/xlib-display-server/src/lib.rs, display-servers/xlib-display-server/src/xwrap.rs, display-servers/xlib-display-server/src/xwrap/window.rs, leftwm-core/src/handlers/command_handler.rs, leftwm-core/src/handlers/command_handler/scratchpad_handler.rs, leftwm/src/bin/leftwm-check.rs, leftwm/src/config.rs, leftwm/src/config/default.rs
- Update Github Action to use same clippy arguments as when running `make test` locally (#1233)
- Fix clippy warnings
=> Update Github Action for Linting, Fix clippy issues

CHANGELOG.md
My name is slightly misspelled. Fix that now.
=> changelog: fix the spelling of my name
